### PR TITLE
Fix typo in user redirect

### LINKED ISSUE #3958: Fix redirect and migration-step for assessment_cycle

### PR DESCRIPTION
**Pull request by sorja**
Refactoring code missed one exclamation mark, caused redirect to break

### CODE REVIEW

File: src/test/migrations/steps/20240919123658-step-update-cycle-props-published-date-status.ts [hunk 1]
```diff
@@ -59,18 +59,12 @@ export default async () => {
...
   await client.query(`
-      do $$
-      begin
-        if exists (
-          select 1
-          from information_schema.columns
-          where table_name='assessment_cycle' and column_name='published'
-        ) then
+        do $$
+        begin
```
Comment (sorja) [inline src/test/migrations/steps/20240919123658-step-update-cycle-props-published-date-status.ts:63]: Simplify the migration by removing double check for `published` column
We already check for `published` above, so no need for double check here.

It was required previously when running this under `public`-migration

**Review by minotogna — APPROVED** [review]
