### PR TITLE
5151 - Admin edit self from country page -> Invalid role shown

### LINKED ISSUE #5151: Admin edit self from country page -> Invalid role shown
When admin edits himself from country page, a wrong form is shown.

Image

**Wrong behavior:** At the moment it shows the Role select field

Image

**Expected behavior:** Show the form fields like when user admin edits himself from admin page

Image

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/client/pages/User/hooks/useRolesFields.ts [hunk 1]
```diff
@@ -65,14 +73,14 @@ export const useRolesFields = (props: PropsFormDefinition): Returned => {
         shouldShow,
         defaultValue: userRoles.filter((role) => role.role === roleName).map((role) => role.countryIso),
         watches: {
-          clearIf: (props) => {
+          clearIf: (props): { shouldClear: boolean; clearValue: unknown } => {
```
Comment (minotogna) [inline src/client/pages/User/hooks/useRolesFields.ts]: can we use return type from types definitions ? e.g. `ReturnType<typeof FieldDefinition['watches']['clearIf']>` ?

**Review by minotogna — COMMENTED** [review]
code looks good. it will work. just a minor comment on the types.

**Review by minotogna — APPROVED** [review]
