### PR TITLE
3400 - panEuropean table 4_3II: fix Plantation columns validations and calculations

### LINKED ISSUE #3400: panEuropean table_4_3b: fix Planation columns validations and calculations

### PR DESCRIPTION
**Pull request by minotogna**
### Calculations

https://github.com/openforis/fra-platform/assets/1138156/8e9041b3-4824-4601-870f-b99f55109fa4

### Validations

https://github.com/openforis/fra-platform/assets/1138156/be69b4e5-06c7-4f54-89d0-c7e605797a65

### CODE REVIEW

File: src/server/controller/cycleData/updateDependencies/updateCalculationDependencies/updateCalculationDependencies.ts [hunk 1]
```diff
@@ -47,8 +47,17 @@ export const updateCalculationDependencies = (props: Props): ContextResult => {
...
+         * in panEuropean table4.3bII col native_species depends on introduced_species that depends on 4.3I.plantations. but in column orders comes before introduced_species.
+         * Therefore, when introduced_species or 4.3I.plantations change, native_species gets calculated before introduced_species/
+         * TODO: To fix this handle dependencies per column
+         */
+        const colsSorted = row.cols.sort((colA, colB) => {
+          return (colA.props.calcOrder ?? 0) - (colB.props.calcOrder ?? 0)
+        })
         // TODO: TO avoid calculating all columns, handle dependencies per column, not row
-        row.cols.forEach((col) => {
+        colsSorted.forEach((col) => {
```
Comment (minotogna) [inline src/server/controller/cycleData/updateDependencies/updateCalculationDependencies/updateCalculationDependencies.ts:60]: @sorja note this hack. it is necessary for having right calculations order.
we'll really need to have calculation dependencies per column, which is a big task and will be addressed when we get a chance

**Review by sorja — APPROVED** [review]
