### PR TITLE
Initial commit invalidate token

### LINKED ISSUE #1664: Invalidate invalid token
Issue:
Invalidate invalid token (eg. user not found, expired)

Steps to reproduce:
- After migrate-fra UI shows as logged in
- Trying to edit data shows an error

- Error probably related to token persisting, token should be reset if issue fetching user (eg. writing to activity log)

Correct steps:
- Log in
- Migrate fra
- Logged out

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1664 

Description:
Invalidate token when email and/or id fail (eg id fails when yarn migrate-fra ran)

- [x] Discuss what field against validate (example vs `user.id`)

### CODE REVIEW

File: src/server/serverInit.ts [hunk 1]
```diff
@@ -27,6 +28,7 @@ export const serverInit = () => {
   app.use(bodyParser.json({ limit: '5000kb' }))
 
   resourceCacheControl.init(app)
+  app.use(validateToken)
```
Comment (minotogna) [inline src/server/serverInit.ts:31]: Can't this be part of passport middleware when we get the user ?

Comment (sorja) [reply src/server/serverInit.ts:31]: We only get the user when we click login, after that the user is persisted in the token

https://github.com/openforis/fra-platform/blob/0257fb3bee850c88fb55a547546d4b3dd73051fc/src/server/api/auth/login.ts#L47

Comment (sorja) [reply src/server/serverInit.ts:31]: This pr resolves using invalid token (eg mismatch user.id and user.email or missing token.validation which is encrypted)

Comment (minotogna) [reply src/server/serverInit.ts:31]: dont we get the user from passport.deserializeUser? we shouldn't store all user in the token . or what do you think?

Comment (sorja) [reply src/server/serverInit.ts:31]: yes, but is this not called only when logging in?
otherwise in the code we use getRequestUser
https://github.com/openforis/fra-platform/blob/39435d6a07c2734ffae5f42bb14bca3e42c6d965/src/server/utils/requests.ts#L48

lets shortly discuss this matter in daily and agree on action points?

Comment (minotogna) [reply src/server/serverInit.ts:31]: I think it's called at every request , have you tested ?

Comment (sorja) [reply src/server/serverInit.ts:31]: After testing this I can confirm it is *never* called

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
