### PR TITLE
3973 - Data Export doesn't work

### LINKED ISSUE #3973: Data Export doesn't work

### PR DESCRIPTION
**Pull request by sorja**
Video shows data fetching for regions and countries for dashboard and table data (data export)

https://github.com/user-attachments/assets/e59aadb6-c825-4744-b6e7-32ed4d657509

### CODE REVIEW

File: src/client/components/Dashboard/hooks/useGetTableData.ts [hunk 1]
```diff
@@ -23,8 +24,14 @@ export const useGetTableData = (props: Props): void => {
 
   const fetchTableData = useCallback(() => {
     if (dependencies.size > 0) {
-      const propsFetch = { assessmentName, cycleName, countryIso, mergeOdp: true }
-      dispatch(DataActions.getTableData({ ...propsFetch, countryISOs, tableNames: Array.from(dependencies) }))
+      const tableNames = Array.from(dependencies)
+      const propsFetch: GetTableDataProps = { assessmentName, cycleName, countryIso, tableNames, mergeOdp: true }
+
+      // When fetching data for Dashboard region level, include regionCode
+      if (!Areas.isISOCountry(countryIso)) {
```
Comment (minotogna) [inline src/client/components/Dashboard/hooks/useGetTableData.ts:31]: Do we have is region ?

Comment (sorja) [reply src/client/components/Dashboard/hooks/useGetTableData.ts:31]: We have `isRegion` that checks for:

```
export enum RegionCode {
  AS = 'AS',
  EU = 'EU',
  NA = 'NA',
  OC = 'OC',
  AT = 'AT',
  AF = 'AF',
  SA = 'SA',
  FE = 'FE',
  EU27 = 'EU27',
  ECOMIFAC = 'ECOMIFAC',
  UNECE = 'UNECE',
  MP = 'MP',
  ITTO = 'ITTO',
  ASEAN = 'ASEAN',
}
```
Excluding the new global region (`WO`).

We should create separate issue to refactor all usages of `!Areas.isISOCountry` and update the isRegion to include `WO`

I tried to find previous discussion about this in a PR but I couldn't find it

**Review by minotogna — APPROVED** [review]
