### PR TITLE
fixed wrong ClientRoutes key

### LINKED ISSUE #1615: Logout from 2025 error
Screenshot 2022-10-13 at 18 57 07

https://user-images.githubusercontent.com/1138156/195658702-d1bb4a2c-629a-44b2-9432-d5e1f0c92a84.mov

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1615

### CODE REVIEW

File: src/client/pages/Assessment/Assessment.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ const Assessment: React.FC = () => {
 
   if (!assessment) return null
 
-  if (!Authorizer.canView({ countryIso, assessment, cycle, user })) window.location.href = ClientRoutes.root.path
+  if (!Authorizer.canView({ countryIso, assessment, cycle, user })) window.location.href = ClientRoutes.Root.path
```
Comment (sorja) [inline src/client/pages/Assessment/Assessment.tsx:83]: How can we build the application this fails

**Review by sorja — APPROVED** [review]

File: src/client/pages/Assessment/Assessment.tsx (hunk 1 above)
Comment (minotogna) [reply src/client/pages/Assessment/Assessment.tsx:83]: that is a good question, how is it possible?

**Review by minotogna — APPROVED** [review]
