### PR TITLE
panEuropeanIndicatorsView.js: fixed visualization in public view

### LINKED ISSUE #88: PanEuropeanView gives error
- [x] Fix PanEuropeanView in public view

### PR DESCRIPTION
**Pull request by minotogna**
Resolves #88

### CODE REVIEW

File: webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js [hunk 1]
```diff
@@ -36,12 +36,13 @@ class PanEuropeanIndicatorsView extends React.Component {
   }
 
   render () {
-    const {i18n, countryIso, status, questionnaireFileName, userInfo, panEuropean = {}} = this.props
+    const { i18n, countryIso, status, questionnaireFileName, panEuropean = {} } = this.props
```
Comment (sorja) [inline webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js]: Should we use defaultProps?

Comment (minotogna) [reply webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js]: we'll refactor this later
