### PR TITLE
2612 + 2606 - Firefox layout table header borders + Character encoding bug

### LINKED ISSUE #2606: Character Encoding failure
image

Country ISO: `CIV`

### LINKED ISSUE #2612: Firefox layout table header borders (see panEuropean area with forest degradation)

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #2612
close #2606

Screenshot 2023-05-11 alle 17 44 38

### CODE REVIEW

File: src/test/migrations/steps/20230511173240-step-pan-european-degradation-rowspan-fix.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+export default async (client: BaseProtocol) => {
+  const { assessment, cycle } = await AssessmentController.getOneWithCycle(
+    { assessmentName: 'panEuropean', cycleName: '2025' },
+    client
+  )
+
+  const schemaName = Schemas.getName(assessment)
+
+  const table = await client.one<Table>(`select * from ${schemaName}.table where props->>'name' = $1;`, 'table_2_5')
```
Comment (minotogna) [inline src/test/migrations/steps/20230511173240-step-pan-european-degradation-rowspan-fix.ts]: oh wait 😅 pan European is still using panEuropeanSpecs, there we still run the old way. this won't work in that case . didn't realize it was a metadata issue, I thought it was a css problem

Comment (rfontanarosa) [reply src/test/migrations/steps/20230511173240-step-pan-european-degradation-rowspan-fix.ts]: argh, ok, I'll fix it into panEuropeanSpecs

**Review by sorja — APPROVED** [review]

**Review by minotogna — APPROVED** [review]
