### PR TITLE
5793 - PanEuropean fixes

### LINKED ISSUE #5793: PanEuropean: Data export empty labels
Image

- Issue scope
  - Fix labels
  - Fix / check why `select all` is messed up

### PR DESCRIPTION
**Pull request by sorja**
# Section 2.5

image

# Section 3.3

image

# Section 3.4

image

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
@sorja can you please double check fra 2020 works as well ?
This component is used there as well

**Comment by sorja** [comment]
> @sorja can you please double check fra 2020 works as well ? This component is used there as well

image

image

image

File: src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import { SectionRedisRepository } from 'server/cache/repository/section'
+import { TableRedisRepository } from 'server/cache/repository/table'
+import { AssessmentController } from 'server/controller/assessment'
+import { BaseProtocol } from 'server/db/db'
+import { TableRepository } from 'server/db/repository/assessment/table'
+
+const assessmentName = AssessmentNames.panEuropean
+const cycleName = CycleNames._2025
+const tableName = 'table_2_5'
+const columnToExclude = 'unknownMixedDegradation'
```
Comment (sorja) [inline src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts:13]: Hide the column via migration

File: src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  const currentColumnsExport = table.props.columnsExport?.[cycle.uuid] ?? []
+  const columnsExport = {
+    ...table.props.columnsExport,
+    [cycle.uuid]: currentColumnsExport.filter((col) => col !== columnToExclude),
+  }
+
+  await TableRepository.update({ assessment, tableId: table.id, tableProps: { columnsExport } }, client)
+
+  const force = true
+  await SectionRedisRepository.getManyMetadata({ assessment, cycle, force }, client)
```
Comment (minotogna) [inline src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts:28]: Any chance we can update only one section ?

File: src/client/pages/DataExport/ColumnSelect/ColumnSelect.tsx [hunk 3]
```diff
@@ -25,6 +25,22 @@ const ColumnSelect: React.FC<{ columns: Array<string> }> = ({ columns }) => {
...
+    const label = getColumnLabelKeys(column, sectionName, assessmentName)
+      .map((key) => {
+        const result = t(key)
+        // if t(key) === key and key contains dots, it's an untranslated path — treat as empty.
+        return result === key && key.includes('.') ? '' : result
+      })
+      .join(' ')
+      .trim()
+    if (label) acc.push({ label, value: column })
+    return acc
```
Comment (sorja) [inline src/client/pages/DataExport/ColumnSelect/ColumnSelect.tsx:41]: In short, if the column is something else than a number or a translation, return '' and filter it out at line 40

File: src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts (hunk 2 above)
Comment (sorja) [reply src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts:28]: Not supported (out of score of PR)

Explanation: Adding sectionNames would wipe other sections and we'd only have this section...

We can look into it later.

_Developers note: I think we ran into this issue once before_

Comment (minotogna) [reply src/tools/migrations/steps/steps/20260326104629-step-step-paneuropean-2025-exclude-unknown-mixed-degradation-from-export.ts:28]: Yes 👍 remember now

**Review by minotogna — APPROVED** [review]
