### PR TITLE
Fix cycle switcher

### LINKED ISSUE #2444: User with Reviewer roles in 2025 only can't switch cycle
- User is logged with Reviewer roles in 3 countries for 2025 only. he has no roles in 2020.
- Access landing page 2020 or 2025: he can't switch cycle

Image

### PR DESCRIPTION
**Pull request by sorja**
# Not logged
image

# Logged with only 2025 roles and 2020 published
image

### CODE REVIEW

File: src/client/store/user/hooks/index.ts [hunk 1]
```diff
@@ -18,6 +19,16 @@ export const useUserCountries = (): Array<CountryIso> => {
   return user?.roles.filter((role) => cycle.uuid === role.cycleUuid).map((role) => role.countryIso)
 }
 
+export const useUserCycles = (assessment: Assessment): Array<Cycle> => {
+  const user = useUser()
```
Comment (minotogna) [inline src/client/store/user/hooks/index.ts:30]: You can avoid passing assessment here , you can use useAssessment same way you use useUser

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
