### PR TITLE
Generic ODP fixes: labels, calculations, first year empty

### LINKED ISSUE #1967: ODP View: Category 'Other land' must be renamed 'Remaining Land' in cycle 2025
In ODP view the table 1a title includes remaining land, but remaining land is not displayed in the table

image

### LINKED ISSUE #2061: ODP Edit: Other wooded land and Other land do not show values when forest starts with number != 100
https://user-images.githubusercontent.com/1138156/213863490-5cb75531-552e-4149-a59b-1f8c463b4714.mov

### LINKED ISSUE #2062: ODP Edit: Default year must be empty
ODP Edit: Default year must be empty otherwise if it's really 2024 odp doesnt get saved 

https://user-images.githubusercontent.com/1138156/213863101-a412c4f3-9638-4e34-9c47-f356e73cb87e.mov

### LINKED ISSUE #2063: ODP Page: refreshing or accessing page directly gives error
https://user-images.githubusercontent.com/1138156/213863301-c7dabc0b-a69d-44c3-8d48-d6cbd6306cbf.mov

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1967 
Resolves #2061 
Resolves #2063 
Resolves #2062 

# 2025
## Empty first year

image

## Calculations and remaining land -label
**Note**: Other wooded land is not calculated and not updated on the fly !
User must input this field
We cannot know if the field is 0 or unknown, therefore left as is

image

### Video WEBM

[screen-recorder-tue-jan-31-2023-09-19-27.webm](https://user-images.githubusercontent.com/5508251/215692718-404bf771-2c4f-428b-b019-958640ddaa53.webm)

# 2020
image

### CODE REVIEW

File: src/client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx [hunk 1]
```diff
@@ -38,6 +38,8 @@ const OriginalData: React.FC<Props> = (props) => {
   const i18n = useTranslation()
   const countryIso = useCountryIso()
 
+  if (!country) return null
```
Comment (minotogna) [inline src/client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx]: Better to add this at Country page level ?

File: src/i18n/resources/en.js [hunk 2]
```diff
@@ -175,6 +175,7 @@ The FRA team fra@fao.org
     forest: 'Forest',
     otherWoodedLand: 'Other wooded land',
     otherLand: 'Other land',
+    remainingLand: 'Remaining land',
```
Comment (minotogna) [inline src/i18n/resources/en.js]: Don't we have this already ?

Comment (sorja) [reply src/i18n/resources/en.js]: image

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
