### PR TITLE
Biomass stock download endpoint

### LINKED ISSUE #1861: Excel calculator download not working
ExcelCalculatorDownload redirects to home page and doesn’t download

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1861

https://user-images.githubusercontent.com/10047945/207355555-1ac6fd73-f76b-40de-9014-b158bc5e1599.mov

### CODE REVIEW

File: src/meta/api/endpoint/ApiEndPoint.ts [hunk 1]
```diff
@@ -24,6 +24,10 @@ export const ApiEndPoint = {
     resetPassword: () => joinPaths('auth', 'local', 'reset-password'),
   },
 
+  BiomassStock: {
+    download: () => apiPath('biomassStock', 'download'),
+  },
```
Comment (sorja) [inline src/meta/api/endpoint/ApiEndPoint.ts]: Add it under File (see eg. userGuide)

File: src/server/api/api.ts [hunk 2]
```diff
@@ -22,7 +23,7 @@ import { UserApi } from './user'
 export const Api = {
   init: (express: Express): void => {
     AuthApi.init(express)
-
+    BiomassStockApi.init(express)
```
Comment (sorja) [inline src/server/api/api.ts]: This is not needed, use FileApi

File: src/server/api/biomassStock/download.ts [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+    if (fs.existsSync(filePath)) {
+      res.download(filePath, 'BiomassCalculator.xlsx')
+    } else if (lang !== 'en' && fs.existsSync(fallbackFilePath)) {
+      res.download(fallbackFilePath, 'BiomassCalculator.xlsx')
+    } else {
+      res.status(404).send('404 / File not found')
+    }
+  } catch (err) {
+    Requests.sendErr(res, err)
```
Comment (sorja) [inline src/server/api/biomassStock/download.ts]: Use fileApi

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]
