### PR TITLE
3448 - National Data->DataSources: Fix issue saving data

### LINKED ISSUE #3448: National Data->DataSources: Data not saved
https://github.com/openforis/fra-platform/assets/1138156/e854a8fe-c6a4-4841-b805-dad430fa150c

### PR DESCRIPTION
**Pull request by sorja**
https://github.com/openforis/fra-platform/assets/5508251/59c06dc9-b23c-479b-b05b-9e26ef0dabb7

https://github.com/openforis/fra-platform/assets/5508251/da337b17-95a7-448c-8e0c-63a9b4e7c29f

### CODE REVIEW

File: src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx [hunk 1]
```diff
@@ -68,6 +76,11 @@ const EditorWYSIWYG: React.FC<Props> = (props: Props) => {
     [onChange]
   )
 
+  useEffect(() => {
+    if (joditEditor) joditEditor.setReadOnly(disabled)
+    if (joditEditor?.container) joditEditor.toolbarContainer.classList.toggle('toolbar-disabled', disabled)
+  }, [disabled, joditEditor])
+
```
Comment (sorja) [inline src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx]: the actual fix

it was possible also to change the css prop to hide toolbar but it would leave the dashed border, so added css class and set border to unset

Comment (minotogna) [reply src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx]: maybe, it is better to add the classList to the div wrapper 
```tsx
return (<div className={classNames('editorWYSIWYG',{disabled})}>
..
```
and control inside the css &.disabled { .FINDTHEOUTERTOOLBAR { display:none }

Comment (sorja) [reply src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx]: i will try this

Comment (sorja) [reply src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx]: good suggestion and works as expected

(lets verify in review anyway)

**Review by minotogna — APPROVED** [review]
👍
