### PR TITLE
Fix exhaustive-deps issue

### LINKED ISSUE #1527: Data Export: never ending fetch

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1527

### CODE REVIEW

File: src/client/pages/DataExport/ResultsTable/useFetchResults.ts [hunk 1]
```diff
@@ -46,7 +45,8 @@ export const useFetchResults = (props: Props): UseFetchResults => {
     },
   })
 
-  useEffect(fetchResults, [fetchResults, selection])
+  // eslint-disable-next-line react-hooks/exhaustive-deps
+  useEffect(fetchResults, [selection])
```
Comment (minotogna) [inline src/client/pages/DataExport/ResultsTable/useFetchResults.ts:49]: The real bug is the creation of the fetch function . 
We'll address this later

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
