### PR TITLE
Original Data Point: Fix primary forest and plantation forest

### LINKED ISSUE #3037: High priority -  NDP cell value cannot be 0
@minotogna 
**Describe the bug**
This only happens when all the area of national classes for that category are 0 (and no way to enter 0% to update the value), for example:
  NDP cell value(**... of which introduced species**) cannot be 0 when using NDP( for Saint Lucia) in tab 1b

**To Reproduce**
1. Create NDP
2.  All the national classes for that category are 0(example plantation forest)
3.  The overall shows as **empty(Dash)** instead of 0

**Expected behavior**
The value should be calculated as **zero** when all percentages for that catergory is 0%(not empty neither dash).

**Screenshots**

**Priority**
High

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/meta/assessment/originalDataPoint/odps/calc.ts [hunk 1]
```diff
@@ -46,20 +46,56 @@ export const calcTotalSubFieldArea = (props: {
...
+  }
+
   const nationalClasses = originalDataPoint.nationalClasses.filter(
     (nationalClass) =>
       !Objects.isNil(nationalClass.area) &&
       !Objects.isNil(nationalClass[field]) &&
       !Objects.isNil(nationalClass[subField]) &&
       !Objects.isNil(nationalClass[subSubField])
   )
+
```
Comment (sorja) [inline src/meta/assessment/originalDataPoint/odps/calc.ts:98]: Note to self:
- This is now resulting in correct results in ODP
- Revisit this code and clean it up if needed
- Important parts:
  - allowed class (is the class included in the calculation of total)
  - forestPercent: it is required for all calculations and must be larger than zero

File: src/meta/assessment/originalDataPoint/odps/updateNationalClass.ts [hunk 2]
```diff
@@ -33,14 +33,21 @@ const calculateValues = (nationalClass: ODPNationalClass) => {
 
   const rowIsMaxedExtentOfForest = Numbers.eq(Numbers.sum([forestPercent, otherWoodedLandPercent]), 100)
 
+  // if forestPlantationPercent is 0, set forestPlantationIntroducedPercent to 0
+  let _forestPlantationIntroducedPercent = forestPlantationIntroducedPercent
```
Comment (minotogna) [inline src/meta/assessment/originalDataPoint/odps/updateNationalClass.ts:37]: This can be ? : 
It will shorten the code

**Review by minotogna — APPROVED** [review]
