### PR TITLE
5304: Fix Country Last published info: invalid when next cycle is published

### LINKED ISSUE #5304: Country Last published info: invalid when next cycle is published

### PR DESCRIPTION
**Pull request by minotogna**
image

image

image

### CODE REVIEW

File: src/tools/migrations/steps/steps/template.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { BaseProtocol } from 'server/db/db'
 
-export default async (client: BaseProtocol): Promise<void> => {
+export default async (_client: BaseProtocol): Promise<void> => {
```
Comment (sorja) [inline src/tools/migrations/steps/steps/template.ts]: this shouldnt be renamed

File: src/server/db/repository/assessmentCycle/country/getCountryLastPublishedInfo.ts [hunk 2]
```diff
@@ -1,22 +1,42 @@
...
 export const getCountryLastPublishedInfo = async (
   props: Props,
   client: BaseProtocol = DB
 ): Promise<LastPublishedRecord> => {
-  const { assessment, countryIso } = props
+  const { assessment, countryIso, cycle } = props
+
+  const cycleDateCreated = Dates.parseISO(cycle.props.dateCreated)
+
+  let include = true
```
Comment (sorja) [inline src/server/db/repository/assessmentCycle/country/getCountryLastPublishedInfo.ts:29]: can we return true/false from fn without defining it outside?

File: src/tools/migrations/steps/steps/template.ts (hunk 1 above)
Comment (minotogna) [reply src/tools/migrations/steps/steps/template.ts]: Tsc compilation problems . When we create a migration step we remove the _ 

Would that work ?

File: src/server/db/repository/assessmentCycle/country/getCountryLastPublishedInfo.ts (hunk 2 above)
Comment (minotogna) [reply src/server/db/repository/assessmentCycle/country/getCountryLastPublishedInfo.ts:29]: That's iterative . A published cycle can have successor cycles not published . They all must be excluded

File: src/tools/migrations/steps/steps/template.ts (hunk 1 above)
Comment (sorja) [reply src/tools/migrations/steps/steps/template.ts]: update `.eslintignore` is better like it was

Comment (minotogna) [reply src/tools/migrations/steps/steps/template.ts]: @sorja I had to exclude it from both tsconfig and eslintignore https://github.com/openforis/fra-platform/pull/5305/commits/d04d9b26db5f9eb0463576262ffd8ae84759cf20

**Review by sorja — APPROVED** [review]

**Review by sorja — APPROVED** [review]
