### PR TITLE
Fix ODP table (1a, 1b) rendering

### LINKED ISSUE #1874: ITA 2025 Table with ODP not rendering correct data

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1874
Fix inconsistency in ODP Tables 1a and 1b:
Issue:
When adding a new original data point for year before 1990 the UI broke: first 'odp' year showed as 1990, even though selected year was 1985. Fix:
Updated the check to see if current row is included in headers, and not if first of both equal

Includes minor refactor where Table.tsx thead and tbody are separated in their own files

_**Note** video shows rendering still works for other tables and now also for 1a and 1b_

https://user-images.githubusercontent.com/5508251/208087319-b797e92d-d299-4f1c-84ca-750969970a02.mov

### CODE REVIEW

File: src/client/pages/AssessmentSection/DataTable/Table/utils/parseTable.ts [hunk 1]
```diff
@@ -36,8 +36,9 @@ export const parseTable = (props: Props): { headers: Array<string>; table: Table
     return { headers, table }
   }
 
+  // Returns true if we are on header row that contains colNames (eg. '1990' or '% of forest area 2015')
   const isHeaderData = (row: TypeRow): boolean =>
-    row.props.type === RowType.header && headers && headers.length > 0 && row.cols[0].props.colName === headers[0]
+    row.props.type === RowType.header && headers && headers.length > 0 && headers.includes(row.cols[0].props.colName)
```
Comment (sorja) [inline src/client/pages/AssessmentSection/DataTable/Table/utils/parseTable.ts:41]: Only change that matters in this PR

File: src/client/pages/AssessmentSection/DataTable/Table/Table.tsx [hunk 2]
```diff
@@ -54,78 +45,14 @@ const Table: React.FC<Props> = (props) => {
         )}
 
         <table id={table.props.name} ref={tableRef} className="fra-table data-table">
-          <thead>
```
Comment (sorja) [inline src/client/pages/AssessmentSection/DataTable/Table/Table.tsx:57]: Moved to TableHead without changes

File: src/client/pages/AssessmentSection/DataTable/Table/Table.tsx [hunk 3]
```diff
@@ -54,78 +45,14 @@ const Table: React.FC<Props> = (props) => {
...
-                    >
-                      {getColumnName()}
-                    </th>
-                  )
-                })}
-              </tr>
-            ))}
-          </thead>
-
-          <tbody>
```
Comment (sorja) [inline src/client/pages/AssessmentSection/DataTable/Table/Table.tsx:114]: Moved to TableBody without changes

**Review by minotogna — APPROVED** [review]
👍

**Review by rfontanarosa — APPROVED** [review]
