### PR TITLE
5157: DataHistory Fix: table name "c" specified more than once

### LINKED ISSUE #5157: DataHistory: table name "c" specified more than once
https://github.com/user-attachments/assets/6fa6c3ac-95ae-40fc-ba28-170610b89613

### PR DESCRIPTION
**Pull request by minotogna**

### CODE REVIEW

File: src/server/repository/assessmentCycle/data/getTableDataLastApproved.ts [hunk 1]
```diff
@@ -24,15 +24,15 @@ export const getTableDataLastApproved = (props: Props, client: BaseProtocol = DB
...
                    al.target -> 'value' as value,
                    row_number() over (partition by al.target ->> 'colUuid' order by al.time desc) as row_number
             from public.activity_log al
-            left join ${schemaCycle}.country c on al.country_iso = c.country_iso
+            left join ${schemaCycle}.country c          on al.country_iso = c.country_iso
             left join public.assessment a               on al.assessment_uuid = a.uuid
             left join public.assessment_cycle ac        on a.id = ac.assessment_id and al.cycle_uuid = ac.uuid
-            left join ${schemaAssessment}.col c         on (al.target ->> 'colUuid')::uuid = c.uuid
-            left join ${schemaAssessment}.row r         on c.row_id = r.id
+            left join ${schemaAssessment}.col col       on (al.target ->> 'colUuid')::uuid = col.uuid
```
Comment (minotogna) [inline src/server/repository/assessmentCycle/data/getTableDataLastApproved.ts:34]: @sorja when country_summary was removed and added country with the same alias c as col.
Code must be always tested please

**Review by sorja — APPROVED** [review]
