### PR TITLE
5778 - Disassociate user role

### LINKED ISSUE #5778: Disassociate user role
@minotogna 

**Describe the bug**
The roles in FRA 2025 and the latest FRA are interconnected. Updating the contact in the FRA latest will automatically change the corresponding person in FRA 2025, which is not the intended behavior.

**Example**
Indonesia, Bangladesh and Jamaica as mentioned in the email.

### PR DESCRIPTION
**Pull request by sorja**
image

image

### CODE REVIEW

**Comment by minotogna** [comment]
@sorja the confirm message better : 
Are you sure you want to disassociate $user-name as $role from .... ?

**Comment by sorja** [comment]
> @sorja the confirm message better : Are you sure you want to disassociate $user-name as $role from .... ?

Sure, sounds good, here's a screenshot:

image

File: src/client/pages/User/RemoveRole/hooks/useOnClick.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  return useCallback(async () => {
+    const name = Users.getFullName(targetUser)
+    const country = t(Areas.getTranslationKey(countryIso))
+    const cycleLabel = t('common.cycleLabel', { assessmentName, cycleName })
+    const countryRole = Users.getRole(targetUser, countryIso, cycle)
+    const role = t(Users.getI18nRoleLabelKey(countryRole.role))
+    // eslint-disable-next-line no-alert
+    if (!window.confirm(t('editUser.disassociateRoleConfirm', { name, country, role, cycleLabel }))) return
+    const params = { assessmentName, cycleName, countryIso, userUuid: targetUser.uuid }
+    await axios.delete(ApiEndPoint.User.role(), { params })
```
Comment (minotogna) [inline src/client/pages/User/RemoveRole/hooks/useOnClick.ts:39]: Do we want to have a confirm message afterwards: 'User $name successfully disassociated from country assessmentName cyclename' 
What do you think ? Or is it useless ?

File: src/client/pages/User/User.scss [hunk 2]
```diff
@@ -0,0 +1,10 @@
+@use 'src/client/style/partials' as *;
+
+.user-form {
+  max-width: 800px;
+  margin: 0 auto;
+
+  .disassociate-role {
```
Comment (minotogna) [inline src/client/pages/User/User.scss]: What about putting a Flex around form and Disassociate to avoid this margin top ?
And the div user-form becomes Flex

File: src/i18n/resources/en/editUser.json [hunk 3]
```diff
@@ -11,6 +11,8 @@
   "deactivate": "Deactivate",
   "demoteToUser": "Are you sure you want to remove Admin privileges?",
   "disabled": "Disabled",
+  "disassociateRole": "Disassociate User Role",
+  "disassociateRoleConfirm": "Are you sure you want to disassociate {{name}} as {{role}} from {{country}} {{cycleLabel}}?",
```
Comment (minotogna) [inline src/i18n/resources/en/editUser.json]: Let's not forget the translations afterwards @sorja

File: src/server/controller/user/disassociateRole.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+  return client.tx(async (t) => {
+    const role = Users.getRole(target, countryIso, cycle)
+    await UserRoleRepository.remove({ uuid: role.uuid }, t)
+
+    // @ts-ignore
+    // eslint-disable-next-line @typescript-eslint/no-unused-vars
+    const { _: roles, ...userNoRoles } = user
+
+    const activityLog = {
+      target: { user: userNoRoles, countryIso },
```
Comment (minotogna) [inline src/server/controller/user/disassociateRole.ts]: Should we put the deleted role in the target as well? Otherwise we won't know which role was deleted

File: src/server/middleware/auth/user/disassociateRole.ts [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+
+import { CountryRequest } from 'meta/api/request/country'
+import { CountryIso } from 'meta/area/countryIso'
+import { Authorizer } from 'meta/auth/authorizer'
+
+import { UserController } from 'server/controller/user'
+import { _next } from 'server/middleware/auth/_next'
+import { Requests } from 'server/utils'
+
+export const requireDisassociateUserRole = async (
```
Comment (minotogna) [inline src/server/middleware/auth/user/disassociateRole.ts]: Since we use the disable user authorizer , should we use the middleware as well ? (And we'll remove this one )

File: src/client/pages/User/RemoveRole/hooks/useOnClick.ts (hunk 1 above)
Comment (sorja) [reply src/client/pages/User/RemoveRole/hooks/useOnClick.ts:39]: I would almost allow undoing this action - replace the button with "Undo"  after the action?

And also we should show the notification

File: src/server/controller/user/disassociateRole.ts (hunk 4 above)
Comment (sorja) [reply src/server/controller/user/disassociateRole.ts]: True, now we just saved the user and country without knowing which role he had.

File: src/server/middleware/auth/user/disassociateRole.ts (hunk 5 above)
Comment (sorja) [reply src/server/middleware/auth/user/disassociateRole.ts]: There was no such middleware, that's why this was introduced.

I made it specific to disassociate, so we can make it more generic when there is another similar use to this

What do you think? Do you prefer directly a more generic one? How would you call it?

File: src/client/pages/User/RemoveRole/hooks/useOnClick.ts (hunk 1 above)
Comment (minotogna) [reply src/client/pages/User/RemoveRole/hooks/useOnClick.ts:39]: no no , let's not undo

File: src/i18n/resources/en/editUser.json [hunk 6]
```diff
@@ -11,6 +11,8 @@
   "deactivate": "Deactivate",
   "demoteToUser": "Are you sure you want to remove Admin privileges?",
   "disabled": "Disabled",
+  "disassociateRole": "Disassociate User Role",
```
Comment (minotogna) [inline src/i18n/resources/en/editUser.json]: just spoke with AP. he prefers 'Remove User Role'

Comment (sorja) [reply src/i18n/resources/en/editUser.json]: Sure, sounds better (and clearer/easier to understand)

I'll update accordingly ( - will also updated methods / code)

File: src/i18n/resources/en/editUser.json [hunk 7]
```diff
@@ -11,6 +11,9 @@
   "deactivate": "Deactivate",
   "demoteToUser": "Are you sure you want to remove Admin privileges?",
   "disabled": "Disabled",
+  "removeRole": "Remove User Role",
+  "removeRoleConfirm": "Are you sure you want to remove {{name}} as {{role}} from {{country}} {{cycleLabel}}?",
+  "removeRoleSuccess": "User {{name}} successfully removed from {{assessmentName}} {{cycleName}}",
```
Comment (minotogna) [inline src/i18n/resources/en/editUser.json]: Country is missing . Without country message can be misleading

Comment (sorja) [reply src/i18n/resources/en/editUser.json]: Sure, updated both (confirm, toaster) to use same params now:

```
    const i18nParams = { name, country, role, cycleLabel }

```

**Review by minotogna — APPROVED** [review]
