### PR TITLE
3774 - Fix satellite mosaic drop down menu overlap

### LINKED ISSUE #3774: Satellite image mosaic drop down menu length to be adjusted
opening satellite image mosaic dialog when burned area dialogue is open hides some of the mosaic years under the dialog below.

image

### PR DESCRIPTION
**Pull request by yaguzmang**
Mosaic year control updated and other selects unaffected: 

https://github.com/openforis/fra-platform/assets/41337901/14394297-a721-49c3-ad8a-d833e26d2744

### CODE REVIEW

File: src/client/components/Navigation/NavGeo/SatelliteMosaic/MosaicControl/MosaicControl.tsx [hunk 1]
```diff
@@ -38,6 +38,7 @@ const MosaicControl: React.FC = () => {
       <OptionLabel>{t('common.year')}</OptionLabel>
       <SelectPrimary
         isClearable={false}
+        maxMenuHeight={126} // 4 options with 28px height each, plus half of another option
```
Comment (yaguzmang) [inline src/client/components/Navigation/NavGeo/SatelliteMosaic/MosaicControl/MosaicControl.tsx:41]: Added extra height so it's more obvious that the select is scrollable and has more options.
This:
image

As opposed to this:

image

**Review by minotogna — APPROVED** [review]
