### PR TITLE
auth improvements and fixes

### LINKED ISSUE #1755: Registration process check
- [x] user is invited (new user is created with status invitationPending)
- [x] user is not registered at all and accept invitation
  - [x] using google (verify if exist, add)
  - [x] using local (add)
- [x] user is authenticable only with google and accept invitation
  - [x] using google
  - [x] using local (add)
- [x] user is authenticable only with local and accept invitation
  - [x] using google (verify if exist, add)
  - [x] using local
- [x] user is authenticable with both google and local and accept invitation
  - [x] using google
  - [x] using local
- [x] user is logged in and accept an invitation

### PR DESCRIPTION
**Pull request by rfontanarosa**
part of #1755

https://user-images.githubusercontent.com/10047945/204276634-fc5ccb75-b262-441b-995e-ea4bedfbda7d.mov

### CODE REVIEW

**Review by minotogna — APPROVED** [review]

**Review by minotogna — CHANGES_REQUESTED** [review]
Post videos about use cases fixed

File: src/i18n/resources/en/login.js [hunk 1]
```diff
@@ -23,8 +23,11 @@ module.exports = {
   noMatchPasswords: "Passwords don't match",
   noEmptyPassword: 'Password cannot be empty',
   noShortPassword: 'Password too short',
-  noMatchingUser: "We couldn't find any user matching these credentials.\nMake sure you have a valid FRA account.",
   noMatchingEmail: "We couldn't find any user matching this email.\nMake sure you have a valid FRA account.",
+  noMatchingLocalUser:
+    "We couldn't find any user matching these credentials.\nMake sure you have a valid FRA account or reset your password in case you forget or lose it.",
+  noMatchingProvider:
```
Comment (sorja) [inline src/i18n/resources/en/login.js:29]: was this added in i18n issue

**Review by sorja — APPROVED** [review]

File: src/i18n/resources/en/login.js (hunk 1 above)
Comment (rfontanarosa) [reply src/i18n/resources/en/login.js:29]: yes, they were

**Review by minotogna — APPROVED** [review]
