### PR TITLE
5291 - Dependencies upgrade: React + Redux - Upgrade packages & fix country routes

### LINKED ISSUE #5291: Dependencies upgrade: React + Redux

### PR DESCRIPTION
**Pull request by yaguzmang**

### CODE REVIEW

File: src/client/pages/PageRoutes/hooks/useRoutes.tsx [hunk 1]
```diff
@@ -65,7 +65,11 @@ export const useRoutes = (): Array<RouteObject> => {
               {/* Country */}
               <Route element={<Country />} path={Routes.Country.path.relative}>
                 <Route element={<Navigate replace to={Routes.CountryHome.path.relative} />} index />
-                <Route element={<CountryHome />} path={`${Routes.CountryHome.path.relative}/*`} />
+
+                <Route path={Routes.CountryHome.path.relative}>
+                  <Route element={<CountryHome />} index />
+                  <Route element={<CountryHome />} path="*" />
+                </Route>
```
Comment (yaguzmang) [inline src/client/pages/PageRoutes/hooks/useRoutes.tsx:72]: From the [docs](https://reactrouter.com/upgrading/v6):
> Upgrading from v6
>Update your Code

>If you have any routes with a path + a splat like <Route path="dashboard/*"> that have relative links like <Link to="relative"> or <Link to="../relative"> beneath them, you will need to update your code.

>👉 Split the <Route> into two

>Split any multi-segment splat <Route> into a parent route with the path and a child route with the splat:

```diff
<Routes>
  <Route path="/" element={<Home />} />
-  <Route path="dashboard/*" element={<Dashboard />} />
+  <Route path="dashboard">
+    <Route path="*" element={<Dashboard />} />
+  </Route>
</Routes>
```

This is why the Navlinks in country/home weren't working

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts [hunk 2]
```diff
@@ -34,10 +34,15 @@ export const useDefaultHandleElementSelect = (): Returned => {
...
+      if (!user && isCountry) {
+        const country = countries.find((country) => country.countryIso === areaCode)
         // If the user is not logged in and accessing a region, direct to default cycle
-      } else if (!user && !Areas.isISOCountry(areaCode)) {
+        const {
+          lastPublishedInfo: { cycleName: lastPublishedCycleName },
+        } = country
+
+        cycleName = lastPublishedCycleName
+      } else if (!user && !isCountry) {
```
Comment (yaguzmang) [inline src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: Complying with eslint `Use object destructuring  prefer-destructuring`

Comment (minotogna) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: Is that needed only if the property name is the same ?
It looks better on one line though . Can just this go in one line without destructuring ?

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts [hunk 3]
```diff
@@ -1,5 +1,5 @@
 import { useCallback } from 'react'
-import { useNavigate } from 'react-router-dom'
+import { useNavigate } from 'react-router'
```
Comment (minotogna) [inline src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:2]: Isn't react router dom available anymore ?

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts (hunk 2 above)
Comment (minotogna) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: Can this become cycleName = country.lastPuishedInfo.cycleName ?

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts (hunk 3 above)
Comment (yaguzmang) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:2]: They [simplified the imports](https://reactrouter.com/upgrading/v6#upgrade-to-v7) so now you can get everything from `'react-router'`
image

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts (hunk 2 above)
Comment (yaguzmang) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: That also triggers the rule `error  Use object destructuring  prefer-destructuring`. I was trying other ways but basically the only one that doesn't trigger the rule is something like

```typescript
        const country = countries.find((country) => country.countryIso === areaCode)
        const { lastPublishedInfo } = country
        const { cycleName: lastPublishedCycleName } = lastPublishedInfo
        cycleName = lastPublishedCycleName
 ```
 
 Should I disable the rule for this line and leave it how it was before?

Comment (minotogna) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: Nope. You can the code as per your comment , it's more readable. Thank yiu 😉

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts (hunk 3 above)
Comment (minotogna) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:2]: Nice 😊 thank you

File: src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts (hunk 2 above)
Comment (yaguzmang) [reply src/client/components/AreaSelector/hooks/useDefaultHandleElementSelect.ts:43]: Updated :+1:

**Review by minotogna — APPROVED** [review]
