### PR TITLE
Fix Original Data Point creation: Display ODPs without National Classes in section 1a and 1b

### LINKED ISSUE #1878: ODP EDIT - 1a . Added new ODP without any national class will not be shown in table 1a-1b
TO FIX . Show it in 1a with empty values

### LINKED ISSUE #1879: ODP EDIT: Do not save ODP in Database when there’s no year

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1878 
Resolves https://github.com/openforis/fra-platform/issues/1879

Fixes 2 odp issues:

1. Fix original data point creation
- Initialise the redux store with empty odp but don't persist to db
- Persist to db on first change (= year)

2. getCreateSchemaCycleOriginalDataPointViewDDL: Fix issue with empty original_data_point.national_classes
- Fix issue where jsonb_array_elements would ignore empty arrays (eg. new ODPs without data)

https://user-images.githubusercontent.com/5508251/207889235-a770ffd5-7ed9-4aa1-a526-246a6c30040c.mov

### CODE REVIEW

File: src/client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts [hunk 1]
```diff
@@ -13,6 +13,27 @@ type Props = CycleParams & {
...
+    {
+      params: {
+        countryIso,
+        assessmentName,
+        cycleName,
+        sectionName: 'extentOfForest',
+      },
+    }
+  )
+  dispatch(setOriginalDataPointUpdating(false))
```
Comment (minotogna) [inline src/client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts]: can updateOriginalDataPoint.fulfilled reducer set originalDataPointUpdating to false, to avoid this action dispatch ?

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
