### PR TITLE
Hide regions for unpublished cycles

### LINKED ISSUE #2445: User with Reviewer roles in 2025 only, wrong redirect on edit profile click
- User is logged with Reviewer roles in 3 countries for 2025 only. he has no roles in 2020.
- When click edit profile, gets redirected to last invited cycle instead of showing edit user page

### PR DESCRIPTION
**Pull request by sorja**
image

UI now reflects the backend rules: 
```
  if (Areas.isGlobal(countryIso) || Areas.isRegion(countryIso)) return false
```

### CODE REVIEW

File: src/client/components/PageLayout/Toolbar/Toolbar.tsx [hunk 1]
```diff
@@ -41,8 +41,8 @@ const Toolbar: React.FC = () => {
 
         <AreaSelector
           includeCountries
-          includeGlobals
-          includeRegions
+          includeGlobals={cycle.published}
+          includeRegions={cycle.published}
```
Comment (minotogna) [inline src/client/components/PageLayout/Toolbar/Toolbar.tsx]: can admin still see those ?

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
