### PR TITLE
5239 - Country Selector - Prevent item selection closing entire group

### LINKED ISSUE #5239: Country Selector: Selecting country wrongly collapses Region
When selecting a country, the region is wrongly closed. 
Expected behavior: Leave the region opened . the layout should not change, apart from the checkbox selected

https://github.com/user-attachments/assets/f36901f9-c69a-45b4-addc-4ee5807dae8d

### PR DESCRIPTION
**Pull request by yaguzmang**
https://github.com/user-attachments/assets/fcd886ad-253a-436e-9c81-28b08a633f4d

### CODE REVIEW

File: src/client/components/Inputs/Select/Indicators/CollapsibleGroup/CollapsibleGroup.tsx [hunk 1]
```diff
@@ -33,9 +33,9 @@ export const CollapsibleGroup: React.FC<GroupProps<Option>> = (props: GroupProps
   }
 
   return (
-    // eslint-disable-next-line
-    <div onClick={handleBackgroundClick}>
-      <div className="select__group-collapsible-heading">
+    <div>
+      {/* eslint-disable-next-line */}
+      <div className="select__group-collapsible-heading" onClick={handleHeadingClick}>
```
Comment (yaguzmang) [inline src/client/components/Inputs/Select/Indicators/CollapsibleGroup/CollapsibleGroup.tsx:38]: @sorja In [these changes](https://github.com/openforis/fra-platform/pull/4927/commits/e7e5b545ae6843570273f6138be6dac6441ee2c0#diff-9aa3c6ee5dd588256e9911e37bd52eac93281997c38bf598045070f59d6a25c3R37-R38) we moved the onClick function to the outer div. Maybe I'm missing something?

Comment (minotogna) [reply src/client/components/Inputs/Select/Indicators/CollapsibleGroup/CollapsibleGroup.tsx:38]: it might have been a simple mistake @yaguzmang . (cc @sorja ) I have tested this branch and all is working as expected. I will resolve this comment and approve this pr. thank you both

**Review by minotogna — APPROVED** [review]
