### PR TITLE
calculation fix

### LINKED ISSUE #1641: SDG Indicator 15.2.1->Sub-Indicator 1: update real time not working
When forest area in table 1a is updated by user,  variable  inSDG Indicator 15.2.1->Sub-Indicator 1 is updated as well; but real time update is not shown in the ui, page must be refreshed. check why websocket is not receiving correct update message

Tested in cycle 2025 with Finland. 

see video

https://user-images.githubusercontent.com/1138156/196986430-b1a98a4d-2015-4828-8dc8-57ace7f12e8b.mov

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1641

https://user-images.githubusercontent.com/10047945/197773182-46f31036-6c3c-4f1c-9783-1bfc2eedba56.mov

https://user-images.githubusercontent.com/10047945/197978647-c88fff0c-900a-4eb7-9b51-fa728e2048cf.mov

### CODE REVIEW

File: src/meta/assessment/assessmentMetaCache.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ export type VariablesByTableCache = Record<string, Record<string, VariableCache>
 export interface VariableCache {
   tableName: string
   variableName: string
+  colName?: string
```
Comment (minotogna) [inline src/meta/assessment/assessmentMetaCache.ts]: can u remove this?

**Review by minotogna — CHANGES_REQUESTED** [review]

**Comment by minotogna** [comment]
have you tested if it works by updated 2025 column ? in 2025 cycle ?

File: src/meta/assessment/assessmentMetaCache.ts (hunk 1 above)
Comment (rfontanarosa) [reply src/meta/assessment/assessmentMetaCache.ts]: it is used to filter visitedVariables

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]
