### PR TITLE
fix data source variables

### LINKED ISSUE #2483: DataSources: use option keys for type and variables properties

### LINKED ISSUE #2494: National Data->data sources: add ‘Other (specify in comments)’ option to type of data sources

### LINKED ISSUE #2495: panEuropean: data sources hide WYSIWYG editor

### PR DESCRIPTION
**Pull request by sorja**
Resolves #2494 
Resolves #2495
Resolves #2483

# #2494 

image

# #2495

image

# #2483

image
image

Example output:
```
{
  dataSources: [
    {
      type: 'remoteSensingBasedAssessmentWithGroundTruthing',
      fraVariables: [
        'forest_expansion',
        'afforestation',
        'deforestation',
        'natural_expansion'
      ],
      comments: 'dd',
      year: '2024',
      reference: {
        text: 'Reference to data source'
      },
      uuid: '037f1482-80b1-43c6-9b65-5ee1b1421477'
    }
  ]
}
```

### CODE REVIEW

File: src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx [hunk 1]
```diff
@@ -12,18 +12,34 @@ type Props = {
...
   return (
     <DataColumn className="data-source-column">
       <Autocomplete
+        labelKey="label"
         withArrow
         disabled={disabled}
         onSave={_onChange}
-        value={dataSource.type}
-        items={Object.keys(dataSourceType).map((type) => t(`dataSource.${type}`))}
+        value={dataSource.type ? t(`dataSource.${dataSource.type}`) : ''}
```
Comment (minotogna) [inline src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx:35]: why is the value the label ? shouldn't the value be the key?

File: src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx [hunk 2]
```diff
@@ -24,23 +24,37 @@ const ColumnFraVariable: React.FC<Props> = (props: Props) => {
...
+      value.map((v) => rows[v])
+    )
   }
 
   return (
     <DataColumn className="data-source-column">
-      <MultiSelect disabled={disabled} values={dataSource.fraVariables ?? []} options={rows} onChange={_onChange} />
+      <MultiSelect
+        disabled={disabled}
+        values={Object.entries(rows).reduce((acc, [label, variable]) => {
```
Comment (minotogna) [inline src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx]: can't the rows be directly an array created by the reducer?

**Review by minotogna — COMMENTED** [review]
shouldn't the current data be migrated? this feature is currently in production

File: src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx (hunk 1 above)
Comment (sorja) [reply src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx:35]: it is the _displayValue_ ; the value shown

used here eg. to highlight match
https://github.com/openforis/fra-platform/blob/2c7ca8604c63b586e77cf783702400d5e71f1353/src/client/components/Autocomplete/Autocomplete.tsx#L25-L27

File: src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx (hunk 2 above)
Comment (sorja) [reply src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx]: it was the initial implementation, but the MultiSelect component expects an list of string

https://github.com/openforis/fra-platform/blob/2c7ca8604c63b586e77cf783702400d5e71f1353/src/client/components/MultiSelect/MultiSelect.tsx#L18-L19

We cannot translate in the MultiSelect component by :
https://github.com/openforis/fra-platform/blob/2c7ca8604c63b586e77cf783702400d5e71f1353/src/client/components/MultiSelect/MultiSelect.tsx#L31-L34

...because we have multiple prefixes:

https://github.com/openforis/fra-platform/blob/2c7ca8604c63b586e77cf783702400d5e71f1353/src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx#L27-L36


**dataSourceVariables?.include** contains a list of values to include (eg. "other, specify in comments")


This implementation uses:

```
type Translation = string
type Value = string

Record<Translation, Value>
```

**Comment by sorja** [comment]
Should I update the underlying components (Autocomplete and MultiSelect) in the scope of this PR to take as prop:
`items: Array<{ label, value }>` (or similar)

I think we cannot use translation prefix for all values? (eg. in case of "Other, specify")

**Comment by minotogna** [comment]
> Should I update the underlying components (Autocomplete and MultiSelect) in the scope of this PR to take as prop:
> 
> `items: Array<{ label, value }>` (or similar)
> 
> 
> 
> I think we cannot use translation prefix for all values? (eg. in case of "Other, specify")

Sounds good 👍 Can you take care of it in this pr ?

File: src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx [hunk 3]
```diff
@@ -24,23 +24,33 @@ const ColumnFraVariable: React.FC<Props> = (props: Props) => {
...
-  const rows = table.rows.reduce((acc, row) => {
-    if (row.props.variableName && row.props.type === RowType.data && !_allColumnsCalculated(row)) {
-      const label = t(Cols.getLabel({ cycle, col: row.cols[0], t }))
-      if (!acc.includes(label)) {
-        acc.push(label)
-      }
+  const _filterRow = (row: Row) =>
+    row.props.variableName && row.props.type === RowType.data && !_allColumnsCalculated(row)
+
+  // Get a list of variables to show form the table
```
Comment (minotogna) [inline src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx]: Why not one reduce ?

File: src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx [hunk 4]
```diff
@@ -93,17 +93,20 @@ const Description: React.FC<Props> = (props) => {
...
-    (!isDataSources && !open && text) ||
-    // 2. data source: Show markdown preview if description is not open and it is not read only
-    (isDataSources && !open && !dataSourceTextReadOnly) ||
-    // 3. data source: Show markdown preview if description is open and it is read only (preview of previous cycle) and has text
-    (isDataSources && open && dataSourceTextReadOnly && text)
+    ((!isDataSources && !open && text) ||
+      // 2. data source: Show markdown preview if description is not open and it is not read only
+      (isDataSources && !open && !dataSourceTextReadOnly) ||
+      // 3. data source: Show markdown preview if description is open and it is read only (preview of previous cycle) and has text
+      (isDataSources && open && dataSourceTextReadOnly && text))
```
Comment (minotogna) [inline src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx:109]: How does panEuropean hide the editor ?

Comment (sorja) [reply src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx:109]: panEuropean has no definition for text

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
