### PR TITLE
fix crash when lang null

### LINKED ISSUE #2912: newly invited users have in the database the lang of the user that has invited them
**Describe the bug**
Crash

**To Reproduce**
1. Log in with newly invited

**Expected behavior**
No crash

### PR DESCRIPTION
**Pull request by sorja**
Resolves #2912 

- Cleaned up code and removed onMount

### CODE REVIEW

File: src/client/pages/PageRoutes/hooks/useInitLanguage.tsx [hunk 1]
```diff
@@ -2,28 +2,33 @@ import { useEffect } from 'react'
...
 export const useInitLanguage = (): void => {
+  const user = useUser()
   const language = useLanguage()
   const updateLanguage = useUpdateLanguage()
   const assessment = useAssessment()
+  const lang = getLang(user)
 
   useOnMount(() => {
-    const lang = (Urls.getRequestParam('lang') || localStorage.getItem('i18n/lang') || Lang.en) as Lang
     if (lang !== language) updateLanguage({ lang }).then(() => ({}))
```
Comment (minotogna) [inline src/client/pages/PageRoutes/hooks/useInitLanguage.tsx]: I'm thinking, do we still need this onMount? I suspect not, can you please verify ?

File: src/client/pages/PageRoutes/hooks/useInitLanguage.tsx [hunk 2]
```diff
@@ -2,28 +2,33 @@ import { useEffect } from 'react'
...
+const getLang = (user: User) => {
+  return (Urls.getRequestParam('lang') || localStorage.getItem('i18n/lang') || user?.props?.lang || Lang.en) as Lang
+}
+
 export const useInitLanguage = (): void => {
+  const user = useUser()
   const language = useLanguage()
   const updateLanguage = useUpdateLanguage()
   const assessment = useAssessment()
+  const lang = getLang(user)
```
Comment (minotogna) [inline src/client/pages/PageRoutes/hooks/useInitLanguage.tsx]: also, this getLang might be useless, and better to derive it in the useEffect, so that user is a dependency of the useEffect

**Review by minotogna — APPROVED** [review]
