### PR TITLE
Fix non-odp odp-year dependant calculations

### LINKED ISSUE #1671: Table 1a/1b update: ODP or Cell with correspondent ODP
for 1b condition check that use national data point is active 

1. Case ODP Edit: when editing an ODP, node dependents that are an ODP variable should not be updated and validated, all the others yes.
2. Case Node Value (with correspondent ODP year) Edit: when editing a cell that has a correspondent ODP, dependencies that are ODP variables, should be updated, all the other variables should not.

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1671 

<table>

<tr>
<th> 1. </th>
<td>
Case ODP Edit: when editing an ODP, node dependents that are an ODP variable should not be updated and validated, all the others yes.
</td>
</tr>

<tr>
<td>
Video
</td>
<td>

https://user-images.githubusercontent.com/5508251/203527077-0410cf1c-1f60-4f13-9b4e-0abb9ed5b7e8.mov

Video displays how websocket updates for 1a and 1b are excluded, but correctly shows the update for `originalDataPointValue`

</td>
</tr>

<tr>
 <td> commit </td>
 <td> 6ef34c9
</tr>

</table>
<table>

<tr>
<th> 2. </th>
<td> Case Node Value (with correspondent ODP year) Edit: when editing a cell that has a correspondent ODP, dependencies that are ODP variables, should be updated, all the other variables should not.
</td>
</tr>

<tr>
<td>
Video
</td>
<td>

https://user-images.githubusercontent.com/5508251/203348813-55b3a53d-2014-47d9-8d0f-bd2c0b372637.mov
</td>
</tr>

<tr>
 <td> commit </td>
 <td> 23eadc1 </td>
</tr>

</table>

### CODE REVIEW

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+// we are editing 'under' odp
+
+export const getDependants = async (props: Props) => {
+  const { assessment, cycle, tableName, variableName } = props
+  const _isODPCell = await isODPCell(props)
+  const dependants = assessment.metaCache[cycle.uuid].calculations.dependants[tableName]?.[variableName] ?? []
+  if (!_isODPCell) return dependants
+  return dependants.filter((dependant) =>
+    [TableNames.extentOfForest, TableNames.forestCharacteristics].includes(dependant.tableName as TableNames)
+  )
```
Comment (sorja) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: Main change, how we get dependants
...for an cell that has ODP year and is an 'ODP field'

File: src/server/controller/cycleData/updateOriginalDataPointDependentNodes.ts [hunk 2]
```diff
@@ -4,55 +4,12 @@ import { Sockets } from '@meta/socket'
 import { User } from '@meta/user'
 
 import { getTableData } from '@server/controller/cycleData/getTableData'
+import { originalDataPointVariables } from '@server/controller/cycleData/originalDataPointVariables'
```
Comment (minotogna) [inline src/server/controller/cycleData/updateOriginalDataPointDependentNodes.ts]: preferred relative import

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
+import { CountryIso } from '@meta/area'
+import { Assessment, Cycle, TableNames } from '@meta/assessment'
+
+import { AreaController } from '@server/controller/area'
+import { isODPVariable } from '@server/controller/cycleData/originalDataPointVariables'
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: something we don't need to address now: we should find a better place and/or structure of originalDataPointVariables (talk for the daily)

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  tableName: string
+  variableName: string
+  colName: string
+  isODP?: boolean
+}
+
+export const isODPCell = async (props: Props) => {
+  const { colName, tableName } = props
+  const country = await AreaController.getCountry(props)
+  const odpYears = await OriginalDataPointRepository.getReservedYears(props)
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: two lines above can be a Promise.all

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+  if (![TableNames.forestCharacteristics, TableNames.extentOfForest].includes(tableName as TableNames)) return false
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: this check can happen before reading country and odpReservedYears to avoid those two unnecessary queries.

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+  return country.props.forestCharacteristics.useOriginalDataPoint && odpYears.map(String).includes(colName)
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: this might be wrong in case of table 1a. 1a has odps even when `country.props.forestCharacteristics.useOriginalDataPoint` is false.
correct check should be
```typescript
const useOriginalDataPoint = tableName === TableNames.extentOfForest || country.props.forestCharacteristics.useOriginalDataPoint
return useOriginalDataPoint && odpYears.map(String).includes(colName)
```

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+// If editing ODP,
+// update all dependants found in metaCache
+// but exclude odp variables
+
+// Case2:
+// If table is 1a or 1b
+// and if there is an ODP year
+// and if country.odp = enabled
+// we are editing 'under' odp
+export const getDependants = async (props: Props) => {
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: add return type

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+  const { assessment, cycle, tableName, variableName, isODP } = props
+  const dependants = assessment.metaCache[cycle.uuid].calculations.dependants[tableName]?.[variableName] ?? []
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: we could have some utils `AssessmentMetaCaches.getCalculationsDependants({cycle, tableName, variableName})` (and others). easy to add in this PR ?

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+// Case1:
+// If editing ODP,
+// update all dependants found in metaCache
+// but exclude odp variables
+
+// Case2:
+// If table is 1a or 1b
+// and if there is an ODP year
+// and if country.odp = enabled
+// we are editing 'under' odp
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/getDependants.ts]: can we improve this comment like Case1, explicitly mentioning which dependants get updated? (see reference issue)

File: src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts [hunk 10]
```diff
@@ -1,24 +1,35 @@
 import { Row, VariableCache } from '@meta/assessment'
 import { NodeUpdates } from '@meta/data'
 
+import { getDependants, isODPCell } from '@server/controller/cycleData/persistNodeValue/getDependants'
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts]: if getDependants, isODPCell are used only here, move the file in this folder, and use relative import (relative import also for Props line below :P )

**Review by minotogna — COMMENTED** [review]
good job 👍 👍 

Just minor details in comments

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts (hunk 3 above)
Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/getDependants.ts]: I agree, we can discuss tomorrow in daily

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts (hunk 5 above)
Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/getDependants.ts]: good catch

File: src/server/controller/cycleData/persistNodeValue/getDependants.ts (hunk 9 above)
Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/getDependants.ts]: Seems like dev note left, update to issue note

File: src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts (hunk 10 above)
Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts]: 👍 
moved to under utils/

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
