### PR TITLE
5235 - FRA Platform - Remove ODP years from 1b when ODP is disabled

### LINKED ISSUE #5235: FRA platform - NDP table 1b wrongly shown
**Describe the bug**
When a user adds national data points for Table 1a, the corresponding years are created for Table 1b when the user chooses **not to use the NDP.**, for which the user may not want to add any value to these empty columns. They can not be removed from the user side.

**To Reproduce**
Case of Canada Table 1b

**Screenshots**

Image

Image

Possible solution:
In the coming assessment, users (NCs, ANCs, collaborators, reviewers, and admins) can also choose to remove these columns (**NON-FRA** years) in the front end.

### PR DESCRIPTION
**Pull request by yaguzmang**
Video in Slack

### CODE REVIEW

File: src/client/pages/Section/DataTable/Table/hooks/useParsedTable.ts [hunk 1]
```diff
@@ -41,11 +43,19 @@ export const useParsedTable = (props: Props): Returned => {
...
   const showODP = useShowOriginalDatapoints()
+  const country = useCountry(countryIso)
   const odpYears = useOriginalDataPointYearsWithHistory({ assessmentName, table: _table })
+  const historyLastApprovedIsActive = useHistoryLastApprovedIsActive()
+
   const { print } = useIsPrintRoute()
 
   return useMemo<Returned>(() => {
-    const _props = { assessmentName, countryIso, cycle, odpYears, showODP, table: _table, print }
+    const ignoreOdpYears =
```
Comment (minotogna) [inline src/client/pages/Section/DataTable/Table/hooks/useParsedTable.ts]: @yaguzmang when history is active in 1b and country doesn't use odp, odp columns should not be shown.
With this change they are. I'm about to push the fix on this branch

Comment (yaguzmang) [reply src/client/pages/Section/DataTable/Table/hooks/useParsedTable.ts]: Ah okay :+1: I thought we should show them in case they used ODPs in the past but not anymore

Comment (minotogna) [reply src/client/pages/Section/DataTable/Table/hooks/useParsedTable.ts]: this is my commit https://github.com/openforis/fra-platform/pull/5242/commits/8e765c003ceeb6d246bf57a70687ff9cad4138a0 I will approve this pr if this looks of to you

Comment (yaguzmang) [reply src/client/pages/Section/DataTable/Table/hooks/useParsedTable.ts]: Yes looks good 👍

**Review by minotogna — APPROVED** [review]
