### PR TITLE
4483 - Fix Latest Russian translation

### LINKED ISSUE #4483: fix 'Latest' russian translation
Image

Новейшая ОЛР (for FRA latest)
ОЛР–2025

src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx:62

### PR DESCRIPTION
**Pull request by yaguzmang**
TODO: 
-  [x] Add the Russian translation via crowdin:
  "cycleLabel": "$t({{assessmentName}}.labels.short)–{{cycleName}}",
  "cycleLatestLabel": "$t(common.latest) $t({{assessmentName}}.labels.short)",

### CODE REVIEW

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx [hunk 1]
```diff
@@ -35,8 +39,22 @@ const _cyclesSorter = (cycleA: Cycle, cycleB: Cycle): number => {
...
+  isLatestCycle: boolean,
+  label: string,
+  language: Lang,
+  t: TFunction
+): string => {
+  if (language === Lang.ru) {
+    return isLatestCycle ? `${t('common.latest')} ${label}` : `${label}–${cycleName}`
+  }
+  return `${label} ${isLatestCycle ? t('common.latest') : cycleName}`
+}
```
Comment (sorja) [inline src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: can we avoid this?

Comment (yaguzmang) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: Yes, would 2 new translations be preferable?
one for Label/Latest to handle the Russian case
another one for non-latest, to handle the dash in Russian as well

Comment (minotogna) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: why don't we use interpolation ? https://www.i18next.com/translation-function/interpolation

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ export const usePopoverItems = (): Array<PopoverItem> => {
     if ((isAdmin || !isDataExportView) && user) {
       assessments.forEach((assessment) => {
         const sortedCycles = assessment.cycles.slice().sort(_cyclesSorter)
-        sortedCycles.forEach((cycle) => {
+        sortedCycles.forEach((cycle: Cycle) => {
```
Comment (minotogna) [inline src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: Is the type needed ?

File: src/i18n/resources/en/common.json [hunk 3]
```diff
@@ -18,6 +18,8 @@
   "countries": "Countries",
   "country": "Country",
   "custom": "Custom",
+  "cycleLabel": "{{assessmentLabel}} {{cycleName}}",
+  "cycleLatestLabel": "{{assessmentLabel}} $t(common.latest)",
```
Comment (minotogna) [inline src/i18n/resources/en/common.json]: Can we use $t as well ?

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx (hunk 2 above)
Comment (yaguzmang) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: image
ts complains for me though the commit hooks pass without it. I can remove it :+1:

File: src/i18n/resources/en/common.json (hunk 3 above)
Comment (yaguzmang) [reply src/i18n/resources/en/common.json]: We would need to add new keys for each assessment, something like 
 ``` 
 "cycleLatestLabelFra": "$t(fra.labels.short) $t(common.latest)",
 "cycleLatestLabelPanEu": "$t(panEuropean.labels.short) $t(common.latest)",
```
or pass the label translation key and do something like:
```
"cycleLatestLabel": "$t({{assessmentLabelKey}}) $t(common.latest)"
```
but that adds some complexity

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx (hunk 2 above)
Comment (minotogna) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: Can u check the sort function instead ?
Do not let ts complain .
Mine was a question

File: src/i18n/resources/en/common.json (hunk 3 above)
Comment (minotogna) [reply src/i18n/resources/en/common.json]: Nope , that's not what I meant

Can u use something like 
$t({{assessmentName}}.labels.short) ....

Comment (yaguzmang) [reply src/i18n/resources/en/common.json]: Yes, added :+1:

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx (hunk 2 above)
Comment (yaguzmang) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/usePopoverItems.tsx]: It went away on its own after latest commit, I think it was just my code editor acting up momentarily. No fix needed
image

**Review by minotogna — COMMENTED** [review]
Looks good to me 
@sorja u want to have a final look ?

**Review by sorja — APPROVED** [review]
