### PR TITLE
2565 + 2566 - Autocomplete fixes

### LINKED ISSUE #2565: AutoCompleteInput - Value MUST be selected from the list
Value which matches with the search string is not automatically selected. It must be selected from the list to make it effective. This is confusing.

Bug found by Chiara Patriarca

https://user-images.githubusercontent.com/10047945/234279715-201370ae-1a71-4d6b-ab32-e86ddf8afa40.mov

### LINKED ISSUE #2566: AutoCompleteInput - Paste from excel doesn't work
https://user-images.githubusercontent.com/10047945/234280849-bc8cf085-8d73-489c-accc-3c275b9c6bd0.mov

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #2565
close #2566

https://user-images.githubusercontent.com/10047945/235712097-67b4c0a0-43ed-47b7-98a8-e69df4d46aa1.mov

https://user-images.githubusercontent.com/10047945/235711882-645d27fb-d422-4d02-ac9f-c47350bb82eb.mov

### CODE REVIEW

File: src/client/components/Autocomplete/Autocomplete.tsx [hunk 1]
```diff
@@ -16,6 +17,7 @@ type Option = {
 type Props = {
   items: Array<Option>
   onSave: (value: string | any) => void
+  onPaste?: OnPaste
```
Comment (minotogna) [inline src/client/components/Autocomplete/Autocomplete.tsx]: It would be preferred not to import a type from that path.
Can it be defined inline directly ? ( in two points in this pr ) 
What do you think ?

File: src/client/components/Autocomplete/AutocompleteInput.tsx [hunk 2]
```diff
@@ -3,17 +3,19 @@ import React from 'react'
...
 import Icon from '@client/components/Icon'
+import { OnPaste } from '@client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange'
 
 type Props = {
   getInputProps: (options?: UseComboboxGetInputPropsOptions, otherOptions?: GetPropsCommonOptions) => any
   value: string
   disabled: boolean
   isOpen: boolean
   openMenu: () => void
+  onPaste: OnPaste
```
Comment (sorja) [inline src/client/components/Autocomplete/AutocompleteInput.tsx]: Should this be optional? Isn't this file used also in DataSources?

File: src/client/components/Autocomplete/Autocomplete.tsx [hunk 3]
```diff
@@ -52,6 +54,7 @@ const Autocomplete: React.FC<Props> = (props: Props) => {
     ) {
       // Disable saving if selected item is not changed when free text disabled
       if (readOnlyOptions && !changes.selectedItem) {
+        onSave({ value: items.find(({ value }) => value === inputValue) ? inputValue : '' })
```
Comment (sorja) [inline src/client/components/Autocomplete/Autocomplete.tsx]: Should this return instead the matched value?

Comment (rfontanarosa) [reply src/client/components/Autocomplete/Autocomplete.tsx]: yes, but always in the form {value: string}. using only string is accepted by Taxon but not by DataSource

**Review by sorja — APPROVED** [review]

**Review by minotogna — APPROVED** [review]
