### PR TITLE
3840 - Fix fetch external dependencies data auth

### LINKED ISSUE #3840: panEuropean: user not authorized error
Image

### PR DESCRIPTION
**Pull request by minotogna**
https://github.com/openforis/fra-platform/assets/1138156/21e31ca6-757c-48d6-84b4-32a002f1c328

### CODE REVIEW

File: src/client/pages/Admin/Admin.tsx [hunk 1]
```diff
@@ -30,10 +30,10 @@ const sections: Array<Section> = [
     name: SectionNames.Admin.userManagement,
     labelKey: 'landing.sections.userManagement',
   },
-  {
-    name: SectionNames.Admin.links,
-    labelKey: 'landing.links.links',
-  },
+  // {
+  //   name: SectionNames.Admin.links,
```
Comment (sorja) [inline src/client/pages/Admin/Admin.tsx:34]: Links disabled?

Comment (minotogna) [reply src/client/pages/Admin/Admin.tsx:34]: Yes, there is memory overflow on Heroku and the app crashes . We need to check that when @yaguzmang will be back .
For now it must be disabled

**Review by sorja — APPROVED** [review]
