### PR TITLE
fixed store to support more than one table per section + optimisation

### LINKED ISSUE #1170: Store data by table name in store

### PR DESCRIPTION
**Pull request by rfontanarosa**
fix #1170

### CODE REVIEW

File: server/controller/cycleData/getTableData.ts [hunk 1]
```diff
@@ -3,17 +3,20 @@ import { CountryIso } from '@meta/area'
...
     cycle: Cycle
-    tableNames: Array<string>
+    sectionName: string
   },
   client: BaseProtocol = DB
 ): Promise<TableData> => {
-  const { countryIso, tableNames, assessment, cycle } = props
+  const { countryIso, assessment, cycle, sectionName } = props
+
+  const tableNames = await TableSectionRepository.getTableNames({ sectionName, assessment })
```
Comment (minotogna) [inline server/controller/cycleData/getTableData.ts:19]: this method belongs to ```SectionRepository.getTableNames```

**Review by minotogna — CHANGES_REQUESTED** [review]

File: client/pages/Assessment/pages/Section/components/DataTable/DataTable.tsx [hunk 2]
```diff
@@ -48,15 +46,15 @@ const DataTable: React.FC<Props> = (props) => {
...
+    //     assessmentName,
+    //     countryIso,
+    //     tableNames: [table.props.name],
+    //     cycleName: cycle.name,
+    //     section: sectionName,
+    //   })
+    // )
     return () => {
       dispatch(AssessmentSectionActions.resetData())
     }
```
Comment (minotogna) [inline client/pages/Assessment/pages/Section/components/DataTable/DataTable.tsx:60]: remove this hook

**Review by minotogna — CHANGES_REQUESTED** [review]

**Review by minotogna — APPROVED** [review]
