### PR TITLE
4329 - of which introduced fix

### LINKED ISSUE #4329: ODP: of which introduced species
Image

Errornous COUNTRY:ODP

| country\_iso | year |
| :--- | :--- |
| BHS | 1986 |
| LCA | 2017 |
| CYM | 2006 |
| DMA | 2000 |
| CUW | 1989 |
| CYP | 2017 |
| CYP | 2005 |
| CYP | 2015 |
| CYP | 2016 |
| PRY | 2013 |
| CYP | 1990 |
| DMA | 2005 |
| DMA | 2018 |
| DMA | 2015 |
| DMA | 2010 |
| BRB | 2001 |
| POL | 2020 |
| ASM | 1986 |
| CYP | 2000 |
| CYP | 2010 |
| MSR | 2019 |
| KGZ | 1990 |
| KGZ | 1993 |
| KGZ | 1998 |
| KGZ | 2003 |
| LCA | 2016 |
| LCA | 2018 |
| LCA | 2019 |
| LCA | 2020 |
| MSR | 1982 |
| PRI | 2009 |
| PRI | 2014 |
| PRI | 2019 |
| PRI | 2004 |
| PRY | 2002 |
| VIR | 2004 |
| VIR | 2009 |
| VIR | 2014 |
| MSR | 2016 |

### PR DESCRIPTION
**Pull request by sorja**
when
plantationForestArea = 0
then
plantationForestIntroducedArea = 0

### CODE REVIEW

File: src/test/migrations/steps/20250205112451-step-of-which-introduced.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  await client.query(`
+    update ${schemaName}.original_data_point
+    set values = values || '{"plantationForestIntroducedArea": "0"}'
+    where
+      values ->> 'plantationForestArea' = '0' and
+      values ->> 'plantationForestIntroducedArea' is null;
+  `)
+
+  await AssessmentController.generateDataCache({ assessment, cycle, force: true }, client)
+  await updateODPDependencies({ assessment, cycle })
```
Comment (minotogna) [inline src/test/migrations/steps/20250205112451-step-of-which-introduced.ts]: I'm thinking that we dont need to update the dependencies ?

**Review by minotogna — APPROVED** [review]
