### PR TITLE
4391 - Pan-European Reasonableness Check 3.2 Table fix

### LINKED ISSUE #4391: Pan-European Reasonableness Check 3.2 Table fix
- [ ] Fix Pan-European 3.2 Reasonableness Check as per following image:

Image

### PR DESCRIPTION
**Pull request by yaguzmang**
(UPDATED)

image

The variableNames that were there before are kept (e.g ` "variableName": "roundwoodRemovalAsPctOfGrowingStockSupply_2010"}`)
also, the only colName and calculateFn that were there for the cols are kept, e.g: `"colName": "FAWS"` 
` "calculateFn": {"uuid": "table_3_2._of_which_forest_available_for_wood_supply_2010.net_annual_increment / (table_1_2a.total_forest_and_other_wooded_land_2010.total * 1000)"}}`

TODO:
- [x] FOWL calculateFn 
- [x] UI adjustments (like centering the '%' symbol)
- [x] Other adjustments as seen fit by the team

### CODE REVIEW

File: src/test/migrations/steps/20250222015809-step-panEuropean-2025-reasonability-check-3-2-fix.ts [hunk 1]
```diff
@@ -0,0 +1,359 @@
...
+    }
+    const year = years[Number(rowProps.index)]
+    const yearCols = getRoundwoodTotalYearsCols(year, cycle.uuid)
+    yearCols.forEach(async (colProps) => {
+      await ColRepository.create({ assessment, cycles: [cycle], row, colProps }, client)
+    })
+  })
+
+  // 5. Generate cache
+  await AssessmentController.generateMetadataCache({ assessment }, client)
```
Comment (minotogna) [inline src/test/migrations/steps/20250222015809-step-panEuropean-2025-reasonability-check-3-2-fix.ts]: No need for this . As the hidden section will remain hidden .

The generate metaCache instead should be executed

**Comment by minotogna** [comment]
@yaguzmang @sorja  (calculations executed separately ) 
Screenshot 2025-03-04 at 15 51 14

File: src/i18n/resources/en/panEuropean/panEuropean.json [hunk 2]
```diff
@@ -1013,11 +1013,13 @@
...
     "netAnnualIncrementPerHa": "Net annual increment per ha (3.1/1.1a) - {{year}}",
     "reasonabilityCheck": "Reasonableness check",
-    "roundwoodRemovalAsPctOfGrowingStockSupply": "Roundwood removals as percent of growing stock on Forest available for wood supply (3.2 / 1.2a) - {{year}}",
-    "roundwoodRemovalAsPctOfGrowingStockTotal": "Roundwood removals as percent of growing stock on Forest and Other wooded land (3.2 / 1.2a) - {{year}}",
+    "roundwoodRemovalAsPctOfGrowingStockSupply": "Roundwood removals as percent of Growing stock on Forest available for wood supply (3.2 / 1.2a)",
+    "roundwoodRemovalAsPctOfGrowingStockTotal": "Roundwood removals as percent of Growing stock on Forest and Other wooded land (3.2 / 1.2a)",
     "soilCarbon": "Soil carbon (1.4a/1.1a) - {{year}}",
     "totalWithDamageOverTotal": "Area with damage as a share of Total forest area (2.4/1.1a) - {{year}}",
-    "variable": "Variable - Year"
+    "unit": "Unit",
```
Comment (sorja) [inline src/i18n/resources/en/panEuropean/panEuropean.json:1020]: Unit already translated?

Comment (minotogna) [reply src/i18n/resources/en/panEuropean/panEuropean.json:1020]: yes several times  actually .can we address these repeated labels in future tasks ?

**Review by sorja — APPROVED** [review]
🦉
