### PR TITLE
4266 - pdf   page space

### LINKED ISSUE #4266: PDF - page space
@minotogna 

**Describe the bug**
In the PDF, some pages have a lot of empty space that could contain all the content of the next page(In some cases, the entire page is blank).

**To Reproduce**
Examples:
Zambia PDF:
2d carbon stock; 7 Non wood forest products removals and value 2020

Yemen PDF:
Table 1a NDP

**Expected behavior**
Wherever possible, keep the necessary space between sub-components of a section, avoiding excessive empty space in the middle.

**Screenshots**
Zimbia:
Image

Image

Yemen:

Image

### PR DESCRIPTION
**Pull request by sorja**
Resolves #4266

### CODE REVIEW

File: src/client/pages/Section/Section.tsx [hunk 1]
```diff
@@ -97,7 +97,6 @@ const Section: React.FC<Props> = (props: Props) => {
                     sectionName={sectionName}
                     table={table}
                   />
-                  {table.props.print?.pageBreakAfter && <div className="page-break" />}
```
Comment (minotogna) [inline src/client/pages/Section/Section.tsx:100]: do we want to remove this from the Table.props definition as well?

Comment (sorja) [reply src/client/pages/Section/Section.tsx:100]: yes, next pr ok?

Comment (minotogna) [reply src/client/pages/Section/Section.tsx:100]: sure

**Review by minotogna — APPROVED** [review]
This is a very nice improvement @sorja 🫶🏼
