### PR TITLE
5385: Client/styles cleanup: checkbox + Fix Status confirm Notify Users list disappear

### LINKED ISSUE #5385: Client/styles cleanup: checkbox

### PR DESCRIPTION
**Pull request by minotogna**

### CODE REVIEW

File: src/client/components/PageLayout/Toolbar/Status/StatusConfirm/StatusConfirm.tsx [hunk 1]
```diff
@@ -42,54 +34,36 @@ const StatusConfirm: React.FC<Props> = (props) => {
...
-            tabIndex={0}
-          >
-            <div className={classNames('fra-checkbox', { checked: !notifyUsers })} />
-            {i18n.t('navigation.doNotNotifyUsers')}
-          </div>
-        )}
-        {notifyUsers && <UserList status={status} />}
-        <div
-          className="nav-assessment-status-confirm__notify-self"
+        <NotifyUsers notifyUsers={notifyUsers} setNotifyUsers={setNotifyUsers} status={status} />
```
Comment (minotogna) [inline src/client/components/PageLayout/Toolbar/Status/StatusConfirm/StatusConfirm.tsx:54]: when admin clicked on Don't notify Users. the user list and checkbox disappeared completely without giving the possibility to rollback the selection.

**Review by sorja — APPROVED** [review]
