### PR TITLE
home country link fix and minor changes

### LINKED ISSUE #1610: Home country link broken

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1610

### CODE REVIEW

**Review by minotogna — APPROVED** [review]

File: src/client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.tsx [hunk 1]
```diff
@@ -57,7 +60,7 @@ const StatusConfirm: React.FC<Props> = (props) => {
             role="button"
             tabIndex={0}
           >
-            <div className={`fra-checkbox${notifyUsers ? '' : ' checked'}`} />
+            <div className={classNames('fra-checkbox', { checked: notifyUsers })} />
```
Comment (sorja) [inline src/client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.tsx]: !notifyUsers

**Review by sorja — CHANGES_REQUESTED** [review]
check classNames works in changes

**Review by sorja — APPROVED** [review]
