### PR TITLE
Fix growingstock 2020

### LINKED ISSUE #2956: App crash on navigating to Growing Stock 2020
**Describe the bug**
App crash on navigating to Growing Stock 2020

**To Reproduce**
1. Go to 2020 growingstock

### PR DESCRIPTION
**Pull request by sorja**
image

sectionSpec had a typo defining 2025 validatieFn to 2020

### CODE REVIEW

File: src/test/migrations/steps/20230818101712-step-fra-2020-growingStockComposition-validator-fix.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  await client.query(`
+      update ${schemaAssessment}.row r
+      set props = props #- '{validateFns}'
+      from (select r2.id
+            from ${schemaAssessment}.row r2
+                     left join ${schemaAssessment}."table" t on r2.table_id = t.id
+            where t.props ->> 'name' = '${tableName}'
+              and r2.props ->> 'variableName' = '${variable}') r2
+      where r.id = r2.id;
+  `)
```
Comment (minotogna) [inline src/test/migrations/steps/20230818101712-step-fra-2020-growingStockComposition-validator-fix.ts:28]: Generate meta cache might be needed here ?

Comment (sorja) [reply src/test/migrations/steps/20230818101712-step-fra-2020-growingStockComposition-validator-fix.ts:28]: Good catch

**Review by minotogna — APPROVED** [review]
