### PR TITLE
5153 - Fix CountrySummaryRepository getOneOrNone

### LINKED ISSUE #5153: CountrySummaryRepository.getOneOrNone: syntax error at or near "$"
https://github.com/user-attachments/assets/757e8290-7a8f-49bd-8181-8bed12950620

### PR DESCRIPTION
**Pull request by yaguzmang**
https://github.com/user-attachments/assets/c3856616-daec-4573-9c54-9807b79e2aee

### CODE REVIEW

File: src/server/repository/assessmentCycle/countrySummary/getOneOrNone.ts [hunk 1]
```diff
@@ -12,10 +13,11 @@ type Props = {
   assessment: Assessment
   countryIso: CountryIso
   cycle: Cycle
+  lang?: Lang
 }
 
 export const getOneOrNone = async (props: Props, client: BaseProtocol = DB): Promise<CountrySummary | null> => {
-  const { assessment, countryIso, cycle } = props
+  const { assessment, countryIso, cycle, lang = Lang.en } = props
```
Comment (minotogna) [inline src/server/repository/assessmentCycle/countrySummary/getOneOrNone.ts]: Logically to get one country the lang shouldn't be needed at all .

Would it be possible to add a parameter to the base query to exclude the lang sorting ?

Comment (minotogna) [reply src/server/repository/assessmentCycle/countrySummary/getOneOrNone.ts]: Or wait , check if this method is needed .
In the history controller , maybe we can get the country from country repository directly ? Can you please check if using the latter we have all needed information ?

**Review by minotogna — APPROVED** [review]
