### PR TITLE
5144 - Dashboard Country 2025: Fix Forest area within protected areas, 2025, % of forest area

### LINKED ISSUE #5144: Dashboard Country 2025: Fix Forest area within protected areas, 2025, % of forest area
Fix forestArea variable name used in 2025 country dashboard

### PR DESCRIPTION
**Pull request by sorja**
image

### CODE REVIEW

File: src/tools/migrations/steps/steps/metadata/dashboard/forestAreaWithinProtectedAreas/index.ts [hunk 1]
```diff
@@ -35,13 +35,16 @@ export const forestAreaWithinProtectedAreas = (cycle: Cycle, region: boolean): D
       id: 2,
       variableName: 'forestArea',
       label: { key: `statisticalFactsheets.rowName.other` },
-      calculateFn: `${TableNames.extentOfForest}.forestArea${is2025 ? '__protectedArea' : ''} ${
+      calculateFn: `${TableNames.extentOfForest}.forestArea${is2025 && region ? '__protectedArea' : ''} ${
```
Comment (sorja) [inline src/tools/migrations/steps/steps/metadata/dashboard/forestAreaWithinProtectedAreas/index.ts:38]: the fix

**Review by minotogna — DISMISSED** [review]

**Review by minotogna — APPROVED** [review]
