### PR TITLE
4547 - PDF - Fix tables overlapping with page number

### LINKED ISSUE #4547: PDF - Table Overlapping with Page Number
@minotogna

**Describe the bug**
Part of user-gernerated table overlapped with the page number, expecially with the long tables. 

**To Reproduce**
Example:
[Indonesia](https://unfao-my.sharepoint.com/personal/fra-platform_fao_org/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Ffra%2Dplatform%5Ffao%5Forg%2FDocuments%2Ffra%2D2025%2Dreports%5F2025%2D03%2D24%2Ffra%2D2025%2DIDN%5Fen%2Epdf&parent=%2Fpersonal%2Ffra%2Dplatform%5Ffao%5Forg%2FDocuments%2Ffra%2D2025%2Dreports%5F2025%2D03%2D24) page 49, 50, 52...

Weirely, seems not always a same pattern: for example page 51,54

**Expected behavior**
Some space is expected between user-entered content and page numbers, or at the very least, they should not overlap.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by yaguzmang**
Pasted Graphic 14

--

Pasted Graphic 13

### CODE REVIEW

File: src/server/service/pdfReport/generate.ts [hunk 1]
```diff
@@ -27,16 +27,15 @@ const defaultProps: Partial<Props> = {
...
 const pdfOptions: PDFOptions = {
   displayHeaderFooter: true,
   footerTemplate: `
-    <div style="width: 100%; font-size: 8px; text-align: center; color: #939393;">
-      <div style="margin-top: 12px;">
-        <span class="pageNumber"></span>
-      </div>
+    <style>#footer { padding: 0 !important; }</style>
+    <div style="width: 100%; height: ${marginBottom}; position: relative; font-size: 8px; text-align: center; color: #939393;">
+      <span class="pageNumber" style="position: absolute; top: 50%; transform: translateY(-50%);"></span>
```
Comment (yaguzmang) [inline src/server/service/pdfReport/generate.ts:38]: Reason why it was overlapping: 
1. Puppeteer puts the footer in an area separate from the main content, so the margin-top that was inside didn't create any separation between footer-content.
2. Chromium adds a default padding-bottom to the footer (as seen in this [issue](https://github.com/puppeteer/puppeteer/issues/4132) ), so that makes the footer container be higher than intended (blank space below).

Visualized with borders:
Pasted Graphic 11

Fix: 
Removing the default padding with `<style>#footer { padding: 0 !important; }</style>`, and making the footer height be the same as the pdf margin bottom. 
Pasted Graphic 12

--

Pasted Graphic 13

**Comment by sorja** [comment]
@minotogna looks ok for me

**Review by minotogna — APPROVED** [review]
