### PR TITLE
4753 - Admin edit country in review: Recent activity wrongly shows status update in review

### LINKED ISSUE #4753: Admin edit country in review: Recent activity wrongly shows status update in review
When editing a country in review, updating country last_edit , also wrongly insert an activity log of status update
Double check this method carefully 

Image

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/server/repository/assessmentCycle/countryActivityLog/getMany.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export const getMany = async (props: Props, client: BaseProtocol = DB): Promise<
     `
         select *
         from ${schemaCycle}.${viewName}
+        where target -> 'value' -> 'calculated' is distinct from to_jsonb(true)
```
Comment (sorja) [inline src/server/repository/assessmentCycle/countryActivityLog/getMany.ts:29]: exclude calculated nodes

**Review by minotogna — APPROVED** [review]
