### PR TITLE
Fix empty values in repeat last

### LINKED ISSUE #2696: Table 1b repeat last estimation error: Egpyt -> of which introduced species for FRA years(between 1990 and 2025) is missing.
@minotogna 

Table 1a(NDP issue):

NC enter one NDP and want to **repeat latest**(or choose a year to **prefill** as now) to fill the values for FRA years, for example 2025. But failed.

Not sure if this is a general or country-specific issue, plz take a look

### PR DESCRIPTION
**Pull request by sorja**
# Normal run:
image

- [x] Unit test
- [x] Use Numbers (BigNumber)
- [ ] ~~Allow negative numbers~~

### CODE REVIEW

File: src/server/service/estimates/estimationEngine.ts [hunk 1]
```diff
@@ -104,8 +104,9 @@ export const applyEstimationFunction = (
   field: Field,
   estFunction: (...params: any[]) => BigNumber
 ): number => {
-  const estimated = Number(estFunction(year, pointA.year, pointA[field], pointB.year, pointB[field]))
-  return Number(estimated < 0 ? '0' : estimated)
+  const estimated = estFunction(year, pointA.year, pointA[field], pointB.year, pointB[field])
+
+  return estimated?.isLessThan(0) ? 0 : estimated?.toNumber()
```
Comment (minotogna) [inline src/server/service/estimates/estimationEngine.ts:109]: why can't a value be negative ?

Comment (sorja) [reply src/server/service/estimates/estimationEngine.ts:109]: From legacy, removed

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
