### PR TITLE
Fix validations for 2a | Fix pasting values | Fix prettier stylelint

### LINKED ISSUE #1571: Use Stylelint for css/scss
- [ ] use stylelint (eslint plugin)
- [x] add it to pre-commit

### LINKED ISSUE #1630: 2a wrong validation
verify and fix 2a subcategory validation 
see Finland 2020

### LINKED ISSUE #1637: Paste value into table 1b cell forest column 2017   cycle 2025 - error
https://user-images.githubusercontent.com/1138156/196938262-4eca57ce-0164-4e41-9019-6cb7d78525ed.mov

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1630 

https://user-images.githubusercontent.com/5508251/197204923-cb98ae37-5502-449b-a13d-e69d4d73a9df.mov

Resolves #1637 

https://user-images.githubusercontent.com/5508251/197148110-4feb84fe-f73c-46fd-b339-0634b8e0a6ac.mov

Resolves #1571

### CODE REVIEW

**Review by rfontanarosa — APPROVED** [review]

File: src/test/sectionSpec/fraSpecs.ts [hunk 1]
```diff
@@ -2405,7 +2405,6 @@ export const FraSpecs: Record<string, SectionSpec> = {
                     '(growingStockAvg.naturallyRegeneratingForest * forestCharacteristics.naturalForestArea) / 1000',
                   readonly: false,
                   validateFns: [
-                    `validatorSubCategory(growingStockTotal.forest,[growingStockTotal.naturallyRegeneratingForest,growingStockTotal.plantedForest])`,
```
Comment (minotogna) [inline src/test/sectionSpec/fraSpecs.ts]: this formula should not be removed.

File: src/test/sectionSpec/fraSpecs.ts [hunk 2]
```diff
@@ -2471,7 +2470,7 @@ export const FraSpecs: Record<string, SectionSpec> = {
                   calcFormula: '(growingStockAvg.plantedForest * forestCharacteristics.plantedForest) / 1000',
                   readonly: false,
                   validateFns: [
-                    `validatorSubCategory(growingStockTotal.forest,[growingStockTotal.naturallyRegeneratingForest,growingStockTotal.plantedForest])`,
+                    `validatorSubCategory(growingStockTotal.plantedForest,[growingStockTotal.plantationForest,growingStockTotal.otherPlantedForest])`,
```
Comment (minotogna) [inline src/test/sectionSpec/fraSpecs.ts]: the formula should not be changed. the rule is plantedForest+naturallyRegeneratingForest <= forest

**Review by minotogna — CHANGES_REQUESTED** [review]

File: src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@ export const validatorSubCategory: ExpressionFunction<Context> = {
         Objects.isEmpty(categoryValue) ||
         Numbers.greaterThanWithTolerance(
           categoryValue,
-          Numbers.sum(subCategoryValues?.filter((v) => !Objects.isEmpty(v)))
+          Numbers.sum(subCategoryValues?.filter((v) => !Objects.isEmpty(v))) ?? 0
```
Comment (sorja) [inline src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts]: `Numbers.sum` : returns null if array empty
`Numbers.greaterThanWithTolerance(` : Returns false if compared nullish value

Comment (minotogna) [reply src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts]: The problem is in the logic.
Before greaterThan ensure arguments are not empty. If one of them is empty , then validation is valid .

Leave sum as it was . 

Does it work ?

Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts]: This works and makes sense

**Review by rfontanarosa — APPROVED** [review]

File: src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts [hunk 4]
```diff
@@ -13,6 +13,7 @@ export const validatorSubCategory: ExpressionFunction<Context> = {
     return (categoryValue?: string, subCategoryValues?: Array<string>): NodeValueValidation => {
       const valid =
         Objects.isEmpty(categoryValue) ||
+        !subCategoryValues?.every(Boolean) ||
```
Comment (minotogna) [inline src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts:16]: does it work when category is empty and every subCategoryValues is true ?

Comment (sorja) [reply src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts:16]: Yes, because of the first check?
`Objects.isEmpty(categoryValue) ||`

image

Comment (minotogna) [reply src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts:16]: missed that 😁

**Review by minotogna — APPROVED** [review]
