### PR TITLE
3212 Fix panEuropean countries select

### LINKED ISSUE #3212: panEuropan: edit role in admin page doesn't allow selecting countries
As seen in below video, in panEuropean admin view, it's not possible to update user roles. country selection is empty 

https://github.com/openforis/fra-platform/assets/1138156/82af110f-287c-497d-b3a0-10f92c0efbe9

### PR DESCRIPTION
**Pull request by sorja**
Screenshot 2023-11-09 at 8 49 57

Note:
- Fixes both admin country filtering and user profile edit countries

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
Any chance to make it more dynamic based on metadata we have in store ?

File: src/client/components/UserListFilters/UserListFilters.tsx [hunk 1]
```diff
@@ -3,16 +3,19 @@ import React, { useState } from 'react'
...
 import { useAppDispatch } from 'client/store'
 import { useCountries, useSecondaryRegion } from 'client/store/area'
 import { useFilters, UserManagementActions, useRoleNames } from 'client/store/ui/userManagement'
+import { useCountryRouteParams } from 'client/hooks/useRouteParams'
 
 import CountrySelectModal from '../CountrySelectModal'
 import MultiSelect from '../MultiSelect'
 
 const UserListFilters: React.FC = () => {
+  const { assessmentName } = useCountryRouteParams()
```
Comment (minotogna) [inline src/client/components/UserListFilters/UserListFilters.tsx]: I would use useCycleRouteParams as we use this in admin as well

**Review by minotogna — COMMENTED** [review]
Any chance to make it more dynamic based on metadata we have in store ?

**Review by minotogna — APPROVED** [review]
