### PR TITLE
Copy previous data source entries and fix descriptions

### LINKED ISSUE #1991: Enhancement- Add button(copy previous data sources)
Add an option “Copy previous data sources” in place(National data-data sources) for all tables 1 to 4.
(1d,1e copied from 1c;2b,2c,2d copied from 2a;3b copied from 3a; 4b copied from 4a)

E.g. The data source of the National data in 2b, 2c, and 2d commonly share the same data source sometimes with additional references.  Adding a button to quote the data source of 2a, namely **Copy previous data sources**.

@minotogna

### LINKED ISSUE #2131: Previous text in HTML may not be recognizable
@minotogna 
Maybe we should let the previous text written in html be recognizable since it is not readable.
a

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1991
Resolves #2131 

https://user-images.githubusercontent.com/5508251/216928787-d4690764-9aa2-4bcc-84b9-b3100adb53c9.mov

### CODE REVIEW

File: src/meta/assessment/subSections.ts [hunk 1]
```diff
@@ -20,7 +20,23 @@ const getAnchorsByUuid = (props: { cycle: Cycle; sections: Array<Section> }): Re
...
+  const { subSection, sections } = props
+  const subsections = sections.reduce<Array<SubSection>>((acc, section) => [...acc, ...section.subSections], [])
+  const previousSubsection = subsections.findIndex((s) => s.id === subSection.id) - 1
+  return subsections[previousSubsection]
+}
+
+const getNext = (props: { subSection: SubSection; sections: Array<Section> }): SubSection => {
+  const { subSection, sections } = props
+  const subsections = sections.reduce<Array<SubSection>>((acc, section) => [...acc, ...section.subSections], [])
+  const nextSubsection = subsections.findIndex((s) => s.id === subSection.id) + 1
```
Comment (minotogna) [inline src/meta/assessment/subSections.ts]: this is very risky and unstable for the future. we need an index metadata for the sub sections then

Comment (minotogna) [reply src/meta/assessment/subSections.ts]: this should be done. otherwise we can't merge this

**Review by minotogna — APPROVED** [review]

**Review by rfontanarosa — APPROVED** [review]
