### PR TITLE
hook: useInitApp

### LINKED ISSUE #1766: PanEuropean: App init -> handle assessment name
Init action src/client/store/assessment/actions/initApp.ts 
and init endpoint  src/server/api/init/init.ts
must handle dynamic assessment name.

init action should get it from url (e.g. http://localhost:9000/FE/assessments/pan_european/2020/home/overview) and pass it to the endpoint.
endpoint should return correct assessment

### LINKED ISSUE #1778: Open WO with direct link crash
Opening WO http://localhost:9000/WO/assessments/fra/2020/home/overview with direct link crashes 

Image

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1778 
Resolves #1766

Add hook useInitApp that returns 'appReady' boolean when condition is met and app is ready to use
Only `Assessment.tsx` uses appReady to avoid crash

Hook usage moved to subpages where we have cycleName and assessmentName in url params.

When cycleName and assessmentName change, we refetch needed data.

Some cases:
- Landing page -> Select Finland

Status:
Assessment: FRA
Cycle: 2020
CountryIso: FIN

- Select cycle 2025
Action:
Refetch areas

Status:
Assessment: FRA
Cycle: 2025
CountryIso: FIN

- Select Landing page (Home icon)
Action:
Refetch areas

Status:
Assessment: FRA
Cycle: 2020 (Default)

This resolves issue also with PanEuropean init app

### CODE REVIEW

File: src/client/store/assessment/hooks/useInitApp.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  const countries = useAppSelector((state) => state.assessment.countries)
+  const assessmentSections = useAssessmentSections()
+
+  const appReady = assessment && countries && assessmentSections
+
+  useEffect(() => {
+    if (!assessment?.props.name || assessment?.props.name !== assessmentName) {
+      dispatch(AssessmentActions.initApp({ assessmentName }))
+    }
+  }, [assessment?.props.name, assessmentName, dispatch])
```
Comment (minotogna) [inline src/client/store/assessment/hooks/useInitApp.ts]: This should remain in initApp called only at startup

File: src/client/store/assessment/hooks/useInitApp.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+  useEffect(() => {
+    dispatch(AssessmentActions.getAreas({ assessmentName, cycleName }))
+  }, [assessmentName, cycleName, dispatch])
+
```
Comment (minotogna) [inline src/client/store/assessment/hooks/useInitApp.ts]: And this should be added to all pages through a hook called useInitPage

File: src/client/store/assessment/hooks/useInitApp.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import { useEffect } from 'react'
+import { useParams } from 'react-router-dom'
+
+import { AssessmentName } from '@meta/assessment'
+
+import { useAppDispatch, useAppSelector } from '@client/store'
+import { AssessmentActions, useAssessment, useAssessmentSections } from '@client/store/assessment'
+
+export const useInitApp = () => {
```
Comment (minotogna) [inline src/client/store/assessment/hooks/useInitApp.ts]: this hook can be renamed to:
```
export const useSyncAssessmentPage = ():boolean => {

```

File: src/client/pages/User/User.tsx [hunk 4]
```diff
@@ -4,6 +4,7 @@ import { useParams } from 'react-router-dom'
 import { Users } from '@meta/user'
 
 import { useAppDispatch } from '@client/store'
+import { useInitApp } from '@client/store/assessment/hooks/useInitApp'
```
Comment (minotogna) [inline src/client/pages/User/User.tsx]: import from '@client/store/assessment'. check everywhere

**Review by minotogna — CHANGES_REQUESTED** [review]

**Review by minotogna — APPROVED** [review]

**Review by persas — APPROVED** [review]
