### PR TITLE
4256 - PDF - NDP comments missing

### LINKED ISSUE #4256: PDF - NDP comments missing
@minotogna 

**Describe the bug**
For countries that use NDP, the comments for NDP are not included in the PDF.

**To Reproduce**
Example of China PDF:
there is no **Comments** section after the section of **Original data and reclassification**

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/client/pages/Print/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx [hunk 1]
```diff
@@ -52,6 +54,25 @@ const OriginalDataPointsPrint: React.FC<Props> = (props) => {
         })}
       </div>
 
+      <div className="odp__section-print-mode">
+        <h3 className="subhead">{i18n.t('dataSource.comments')}</h3>
+        <DataGrid className="odp__section" gridTemplateColumns="100px minmax(240px, 40%)">
+          {originalDataPoints.map((originalDataPoint, i) => {
```
Comment (minotogna) [inline src/client/pages/Print/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx:60]: Does it appear at the end of each odp ?

Can we have a screenshot ?

Comment (sorja) [reply src/client/pages/Print/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx:60]: Sent video and screenshot thru slack

**Review by minotogna — APPROVED** [review]
