### PR TITLE
5346 + 5338: Fix TSC Issue:explorer/selection/selectors/index.ts +/Geo/StatisticsSidePanel

### LINKED ISSUE #5346: TSC Issue: src/client/store/explorer/selection/selectors/index.ts
Image

### PR DESCRIPTION
**Pull request by yaguzmang**

### CODE REVIEW

File: src/client/store/explorer/selection/selectors/index.ts [hunk 1]
```diff
@@ -27,21 +30,54 @@ const _baseSelectors = [
...
+  }
+)
 
-const getUnits = createSelector(_baseSelectors, (filters, assessmentName, cycleName, sectionName) => {
-  return filters?.[assessmentName]?.[cycleName]?.units?.[sectionName]
-})
+const getUnits = createSelector(
+  _baseSelectors,
+  (
+    filters: ExplorerSelectionState | undefined,
```
Comment (minotogna) [inline src/client/store/explorer/selection/selectors/index.ts]: Aren't the types inherited ? Why is it needed to specify them ? ( out of curiosity )

Comment (minotogna) [reply src/client/store/explorer/selection/selectors/index.ts]: Ideally the only change should be the get state method .

File: src/client/store/explorer/selection/selectors/index.ts [hunk 2]
```diff
@@ -5,18 +5,21 @@ import { CycleName } from 'meta/assessment/cycle'
 import { SectionName } from 'meta/assessment/section'
 
 import { ExplorerSelectionSlice } from 'client/store/explorer/selection/slice'
+import type { ExplorerSelectionState } from 'client/store/explorer/selection/state'
 import { defaultAxisSelection } from 'client/store/explorer/selection/state'
 import { RootState } from 'client/store/types'
 
-const _getState = (state: RootState) => state.explorer?.[ExplorerSelectionSlice.name]
+const _getState = (state: RootState): ExplorerSelectionState | undefined => {
+  return state.explorer?.[ExplorerSelectionSlice.name]
```
Comment (minotogna) [inline src/client/store/explorer/selection/selectors/index.ts]: Isn't this state[ExplorerSliceName] ?

File: src/client/store/explorer/selection/selectors/index.ts (hunk 1 above)
Comment (minotogna) [reply src/client/store/explorer/selection/selectors/index.ts]: See my pr @yaguzmang

**Review by minotogna — APPROVED** [review]
