### PR TITLE
3363 - Add admin and reviewers as recipients when sending the report for approval & Add notify self feature

### LINKED ISSUE #3363: Add admin and reviewers as recipients when sending the report for approval
@minotogna 

**Describe the bug**
Other reviewers and the admin can't know what has been left when sending reports with comments for approval(see screenshots).

**Expected behavior**
By default, the admin and all reviewers for this country should receive a copy of the comments left when the report is sent for approval.
**Screenshots**
image

### PR DESCRIPTION
**Pull request by yaguzmang**
Adding admin and reviewers as recipients when sending the report for approval, and adding notify-self feature.

TODO:
- Safely test email service. For this PR I tested locally that the email promises are correctly constructed, but didn't send actual emails. 

https://github.com/openforis/fra-platform/assets/41337901/f4ae763e-4ae7-4e99-b2f4-a1a31cb4ba74

### CODE REVIEW

**Comment by minotogna** [comment]
Collaborators , Alternate NC and NC should not be recipient when sending the reports for approval (the issues states only admin and reviewers should). Is this the case in this pr?

**Comment by minotogna** [comment]
@yaguzmang the pr looks good. Please, put it in draft and once you get the translations put it back to review and ask @sorja for his approval.
Thank you!

File: src/i18n/resources/en.js [hunk 1]
```diff
@@ -418,6 +418,7 @@ The FRA team
     cancel: 'Cancel',
     changeStatusTextPlaceholder: 'Add an optional message',
     doNotNotifyUsers: "Don't notify users",
+    notifySelf: 'Send copy to self',
```
Comment (sorja) [inline src/i18n/resources/en.js:421]: Not sure, sounds weird
Maybe:

```suggestion
notifySelf: 'Send a copy to myself',
```

Comment (yaguzmang) [reply src/i18n/resources/en.js:421]: Would we want to requests translations again to keep it consistent? if so, it would take some time. We are still waiting for the French translation.

Comment (sorja) [reply src/i18n/resources/en.js:421]: I think it's fine to change or correct the English one if there is a typo?
All is fine, you can resolve this comment also without changing

File: src/server/repository/public/user/getAdmins.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+  const query = `
+      select ${selectFields}, jsonb_agg(to_jsonb(ur.*) - 'props') as roles
+      from public.users u
+               join public.users_role ur on (u.id = ur.user_id)
+      where ur.role = '${RoleName.ADMINISTRATOR}'
+        and ${statusWhereCondition}
+      group by ${selectFields}
+  `
+
+  return client.manyOrNone<User>(query).then((data) =>
```
Comment (minotogna) [inline src/server/repository/public/user/getAdmins.ts]: Here we usually use client.map . Also do we have UserAdapter directly ? If yes , use that , otherwise no worries we'll add it later

Comment (yaguzmang) [reply src/server/repository/public/user/getAdmins.ts]: It seems we don't have a UserAdapter yet. For Users it seems we only have the UserRoleAdapter.

Comment (minotogna) [reply src/server/repository/public/user/getAdmins.ts]: ok, but let's use client.map at least

Comment (yaguzmang) [reply src/server/repository/public/user/getAdmins.ts]: Added to the latest commit ✌️

**Review by minotogna — APPROVED** [review]
