### PR TITLE
4283 - PDF hide empty graph

### LINKED ISSUE #4283: PDF - graph
@minotogna 

**Describe the bug**
The graph is entirely empty when no data is available. As Örjan suggests, the graph should be removed if it is entirely empty.

Could you please quickly filter out countries that do not have **any of** these data for the main classes (Table 1a: Forest; Other wooded land; Table 1b: Naturally regenerating forest; Plantation forest; Other planted forest) to ensure they are not missed?

**To Reproduce**
Example

Albania PDF - Table 1b graph

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/client/pages/Section/DataTable/DataTable.tsx [hunk 1]
```diff
@@ -38,7 +38,26 @@ const DataTable: React.FC<Props> = (props) => {
...
+      )
+    }
+
+    if (tableName === TableNames.forestCharacteristics) {
+      return ['plantedForest', 'naturalForestArea'].every((variableName) =>
+        RecordAssessmentDatas.isVariableDataEmpty({ ...baseProps, variableName })
+      )
+    }
+    return false
+  }, [baseProps, tableName])
```
Comment (minotogna) [inline src/client/pages/Section/DataTable/DataTable.tsx]: Can we have a hook for this ? More clean maybe

File: src/client/pages/Section/DataTable/DataTable.tsx [hunk 2]
```diff
@@ -47,9 +66,15 @@ const DataTable: React.FC<Props> = (props) => {
     return null
   }
 
+  // Show chart in print only if chart variables are not empty
+  const showChartPrint = showOdpChart && print && !areChartVariablesEmpty
+
+  // By default, show chart always
+  const showChartDefault = showOdpChart && !print
```
Comment (minotogna) [inline src/client/pages/Section/DataTable/DataTable.tsx]: Can we have only one show chart ?

File: src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts [hunk 3]
```diff
@@ -0,0 +1,26 @@
+import { Objects } from 'utils/objects'
+
+import { CountryIso } from 'meta/area'
+import { AssessmentName, CycleName, TableName, VariableName } from 'meta/assessment'
+
+import { RecordAssessmentData } from '../RecordAssessmentData'
+import { getTableData } from './getTableData'
+
+export const isVariableDataEmpty = (props: {
```
Comment (minotogna) [inline src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: Mate a type Props ?

File: src/test/migrations/steps/20250228094002-step-clean-up-descriptions-empty.ts [hunk 4]
```diff
@@ -1,47 +1,70 @@
...
 
-import { Assessment, AssessmentNames } from 'meta/assessment'
+import { Assessment, AssessmentNames, Cycle } from 'meta/assessment'
 
 import { BaseProtocol, Schemas } from 'server/db'
 import { AssessmentRepository } from 'server/repository/assessment/assessment'
 
+const brTagRegex = '<br\\s*/?>'
+
 export default async (client: BaseProtocol) => {
```
Comment (minotogna) [inline src/test/migrations/steps/20250228094002-step-clean-up-descriptions-empty.ts]: This has already been executed . Another migration is needed

File: src/client/pages/Section/DataTable/hooks/useAreChartVariablesEmpty.tsx [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+  return useMemo(() => {
+    const { tableName } = props
+    if (tableName === TableNames.extentOfForest) {
+      return ['forestArea', 'otherWoodedLand'].every((variableName) =>
+        RecordAssessmentDatas.isVariableDataEmpty({ ...props, variableName })
+      )
+    }
+
+    if (tableName === TableNames.forestCharacteristics) {
+      return ['plantedForest', 'naturalForestArea'].every((variableName) =>
```
Comment (minotogna) [inline src/client/pages/Section/DataTable/hooks/useAreChartVariablesEmpty.tsx]: In 1b we have 3 variables if I recall correctly. Can u please check ?

File: src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+export const isVariableDataEmpty = (props: Props): boolean => {
+  const { assessmentName, cycleName, data, tableName, countryIso, variableName } = props
+  const tableData = getTableData({ assessmentName, cycleName, data, tableName, countryIso })
+
+  if (Objects.isEmpty(tableData)) {
+    return true
+  }
+
+  const recordRowData = Object.values(tableData)
+  return Objects.isEmpty(recordRowData.filter((rowData) => rowData[variableName]))
```
Comment (minotogna) [inline src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: Should we check the raw value ?

Maybe an every as well here ?

**Review by minotogna — COMMENTED** [review]
👍minor comments

File: src/client/pages/Section/DataTable/hooks/useAreChartVariablesEmpty.tsx (hunk 5 above)
Comment (sorja) [reply src/client/pages/Section/DataTable/hooks/useAreChartVariablesEmpty.tsx]: I will check the code also, but in UI we can only see 2 I think
https://fra-data.review.fao.org/assessments/fra/latest/FIN/sections/forestCharacteristics

Comment (minotogna) [reply src/client/pages/Section/DataTable/hooks/useAreChartVariablesEmpty.tsx]: yes, I remember that from 2020.
However we have useTrends to get dynamically the variables displayed in the chart.
maybe here we can use the same dynamic approach instead of hardcoding the variables ?
image

File: src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts (hunk 6 above)
Comment (sorja) [reply src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: **I added every - but please note - if we are missing a single value (e.g. forest 2000) the chart will be hidden**

Is this the behavior we want? Should be check _some_ value exists? What if one value only exists?

I think that normally, all values must exist because 1a and 1b are the main tables?

Comment (minotogna) [reply src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: Yes , every is empty 
some is not empty . 
Maybe you're right , let's use some is not empty . The loop will ends before

Comment (sorja) [reply src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: Ah, thank you for the clarification, I initally understood that if _every_ has value instead it should have been if _every_ is empty ;)

Added _some_ has not value

File: src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+export const isVariableDataEmpty = (props: Props): boolean => {
+  const { assessmentName, cycleName, data, tableName, countryIso, variableName } = props
+  const tableData = getTableData({ assessmentName, cycleName, data, tableName, countryIso })
+
+  if (Objects.isEmpty(tableData)) {
+    return true
+  }
+
+  const rowData = Object.values(tableData)
+  return rowData.some((rowData) => !Objects.isEmpty(rowData[variableName]))
```
Comment (minotogna) [inline src/meta/data/recordAssessmentDatas/isVariableDataEmpty.ts]: Does this check value.raw ? The node value can contain metadata but the value can be empty

**Review by minotogna — APPROVED** [review]
