### PR TITLE
Fix: Section 8 - Sub Indicator 4 wrong calculation results

### LINKED ISSUE #3113: Section 8 - Sub Indicator 4 wrong calculation results
AP:
When looking at the approved report of US Virgin Islands, I can see that there’s no data for Table 3b. Despite of that the sub-indicator 4 table under section 8 displays zeros (screenshots below). I think the table should be empty (no data).

Image

Image

### PR DESCRIPTION
**Pull request by sorja**
# TODO: 
- [x] Understand and resolve why redis is behind after flushing

[screen-recorder-thu-oct-05-2023-10-16-24.webm](https://github.com/openforis/fra-platform/assets/5508251/010c1f31-d0de-4695-a53f-2477480eb24f)

### CODE REVIEW

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+  where t.props ->> 'name' = 'sustainableDevelopment15_2_1_4'
+  and r.props ->> 'variableName' = 'proportionForestAreaLongTermForestManagement'
+  and c.props ->> 'colType' = 'calculated'
+  and c.props -> 'calculateFn' ->> '${cycle.uuid}' is not null;
+  `
+  )
+
+  const updatedCols = cols.map((col) => {
+    const { props } = col
+    const calculateFn = `forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan ? ${
```
Comment (minotogna) [inline src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts]: I noticed in the current calculations there are math.min with one single input parameter, cani double check ? Plus , current data must be recalculated

Comment (sorja) [reply src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts]: Sure, I noticed it too, I will remove it and recalculate

Comment (minotogna) [reply src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts]: Please , check the original formula . Also , to have a valid result , all variables involved must have a valid value

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+           left join ${schemaName}.col c on r.id = c.row_id
+  where t.props ->> 'name' = 'sustainableDevelopment15_2_1_4'
+  and r.props ->> 'variableName' = 'proportionForestAreaLongTermForestManagement'
+  and c.props ->> 'colType' = 'calculated'
+  and c.props -> 'calculateFn' ->> '${cycle.uuid}' is not null;
+  `
+  )
+
+  const updatedCols = cols.map((col) => {
+    const calculateFn = `forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan && extentOfForest.forestArea["2015"] ? forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan / extentOfForest.forestArea["2015"] * 100 : null`
```
Comment (minotogna) [inline src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts]: the Math.min has disappeared ? have you checked original formula ?

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+
+  await AssessmentController.generateMetaCache(
+    {
+      assessment,
+      cycle,
+    },
+    client
+  )
+
+  await runCalculations(
```
Comment (minotogna) [inline src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts]: does this work with new way of calculating dependencies ?

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+  const exists = AssessmentMetaCaches.getCalculationsDependants({
+    assessment,
+    cycle,
+    tableName,
+    variableName,
+  }).find((d) => d.tableName === tableName && d.variableName === variableName)
+
+  // make self dependant if it is not already
+  if (!exists) {
+    assessment.metaCache[cycle.uuid].calculations.dependants[tableName] = {
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: actually , the node we are updating here, should be the first in the queue. the best way to ensure it, it probably requires to check if the node exists in the context.queue . try to unshift the node if it's not in the queue (after current line 62)

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+  cycle: Cycle
+  variableName: string
+  tableName: string
+}
+
+export const updateCalculatedVariable = async (props: Props, client: BaseProtocol) => {
+  const { assessment, cycle, variableName, tableName } = props
+
+  // -- flush redis
+  await RedisData.getInstance().flushall()
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: it would be preferable not to flushall every time we updated a variable. why is this needed?

File: src/test/migrations/steps/utils/runCalculations.ts [hunk 6]
```diff
@@ -9,6 +9,9 @@ import { BaseProtocol, Schemas } from 'server/db'
 import { calculateRow } from './calculateRow'
 import { getRow } from './getRow'
 
+/**
+ * @deprecated
+ */
 export const runCalculations = async (
```
Comment (minotogna) [inline src/test/migrations/steps/utils/runCalculations.ts:15]: we should update all migration steps to use this new updateCalulatedVariables. separate task (preferred) ?

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+  and r.props ->> 'variableName' = 'proportionForestAreaLongTermForestManagement'
+  and c.props ->> 'colType' = 'calculated'
+  and (c.props -> 'calculateFn' ->> '${cycle2020.uuid}' is not null or c.props -> 'calculateFn' ->> '${cycle2025.uuid}' is not null)
+  `
+  )
+
+  const updatedCols = cols.map((col) => {
+    let _col = Objects.cloneDeep(col)
+    const valuesExist = `forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan && extentOfForest.forestArea["2015"]`
+    const formula = `Math.min(forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan / extentOfForest.forestArea["2015"] * 100, 100)`
```
Comment (minotogna) [inline src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts:39]: is the year static for all columns?

**Review by minotogna — COMMENTED** [review]
good job @sorja 👍 👍 some comments to discuss

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts (hunk 7 above)
Comment (sorja) [reply src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts:39]: yes

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts (hunk 4 above)
Comment (sorja) [reply src/test/migrations/steps/utils/updateCalculatedVariable.ts]: `15:58:35 error: ERR wrong number of arguments for 'hmget' command`

I think this is when creating the queue and the `rows` is empty here:
https://github.com/openforis/fra-platform/blob/e9886c5179121fb3ec63a49fdab6670489488cf9/src/server/controller/cycleData/updateDependencies/context/contextFactory.ts#L136

That was the previous reason for the workaround, any thoughts?

If I check `this.#rowKeys` value before calling `    const rows = await RowRedisRepository.getRows({ assessment, rowKeys: Array.from(this.#rowKeys) })` it shows:
`rowkeys Set(0) {}`

Because of 

```
      const selfIsDependant = this.#addDependantsToQueue({ tableName, variableName, colName })
      // if self is not dependant of itself, mark it as visited
      if (!selfIsDependant) {
        this.#visitedVariables.push({ variableName, tableName, colName })
      }
```

(Reasoning behind editing the metacache and making self dependant)

What do you suggest?

File: src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts (hunk 7 above)
Comment (minotogna) [reply src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts:39]: All columns have the same result ?

Comment (sorja) [reply src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts:39]: Result changes with value of `forestAreaWithinProtectedAreas.forest_area_with_long_term_management_plan`

**Comment by sorja** [comment]
- [x] update db
- [x] update the row cache
- [x] update calculation result
- [x] persist db
- [x] persist cache

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+        nodes,
+      }
+
+      const contextProps = { assessment, cycle, isODP: false, nodeUpdates }
+      const context = await ContextFactory.newInstance(contextProps)
+
+      const ts = Date.now()
+
+      const { nodesDb } = updateCalculationDependencies({ context, jobId: `migration_step-${ts}` })
+      await NodeRepository.massiveInsert({ assessment, cycle, nodes: nodesDb }, client)
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: the Massive insert can be done after all countries iteration, not one per country

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 9]
```diff
@@ -15,13 +18,28 @@ type Props = {
...
+  const rowKey = RowCaches.getKey({
+    tableName,
+    variableName,
+  })
+
+  const r = (await RowRepository.getManyCache({ assessment })).find(
+    (r) => r.tableName === tableName && r.props.variableName === variableName
+  )
+
+  await redis.hset(key, rowKey, JSON.stringify(r))
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: this is internal to redis repository. add a method there, do not expose

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+      const cycleName = cycle.name
+
+      const nodeUpdates: NodeUpdates = { assessmentName, cycleName, countryIso, nodes: _nodes }
+      const contextProps = { assessment, cycle, isODP: false, nodeUpdates, includeSourceNodes: true }
+      const context = await ContextFactory.newInstance(contextProps)
+      const { nodesDb, nodes } = updateCalculationDependencies({ context, jobId: `migration_step-${Date.now()}` })
+
+      allNodesDb.push(...nodesDb)
+
+      await DataRedisRepository.updateNodes({ assessment, cycle, countryIso, nodes })
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: This should be done after successfully persisted nodes to the db

File: src/test/migrations/steps/utils/updateCalculatedVariable.ts [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+
+        allNodesDb.push(...nodesDb)
+
+        await DataRedisRepository.updateNodes({ assessment, cycle, countryIso, nodes })
+      })
+    )
+  } catch (e) {
+    Logger.error(e)
+  } finally {
+    await NodeRepository.massiveInsert({ assessment, cycle, nodes: allNodesDb }, client)
```
Comment (minotogna) [inline src/test/migrations/steps/utils/updateCalculatedVariable.ts]: what if this fails ?

Comment (minotogna) [reply src/test/migrations/steps/utils/updateCalculatedVariable.ts]: cache must be updated if inserts is successfully executed

**Review by minotogna — APPROVED** [review]
