### PR TITLE
table.js: display csv export if tableRef not null

### LINKED ISSUE #208: Table export
In same cases, table export doesn't work.
Downloaded CSV file is blank. (See AUS 1c, 1d)

### PR DESCRIPTION
**Pull request by sorja**
Resolves #208

### CODE REVIEW

File: webapp/app/assessment/components/dataTable/table/table.js [hunk 1]
```diff
@@ -26,11 +26,12 @@ const Table = (props) => {
   const i18n = useI18n()
   const [printView] = usePrintView()
   const tableRef = useRef(null)
+  const displayTableExportButton = !secondary && !printView && tableRef.current != null
```
Comment (minotogna) [inline webapp/app/assessment/components/dataTable/table/table.js:29]: It's not safe to check tableRef.current != null.
Use React.forwardRef
