### PR TITLE
exact path login

### LINKED ISSUE #147: Reset password
Reset password functionality seems to be broken.
To be fixed in master branch

### PR DESCRIPTION
**Pull request by sorja**
Resolves #147

### CODE REVIEW

File: webapp/login/loginView.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ const LoginView = () => {
             <ResetPasswordForm />
           </Route>
 
-          <Route path="/login/">
+          <Route exact path="/login/">
```
Comment (minotogna) [inline webapp/login/loginView.js]: add exact also to resetPassword.
