### PR TITLE
3772 - Fix Navigating between data tables and GEO

### LINKED ISSUE #3772: Navigating between data tables and GEO
When navigating from a data table to GEO, it would be nice to return back to the same table instead of the dashboard, when switching between the views.

### PR DESCRIPTION
**Pull request by minotogna**
https://github.com/openforis/fra-platform/assets/1138156/cb7819a0-0637-4e08-8de5-14d51620a964

### CODE REVIEW

File: src/client/pages/Geo/Geo.tsx [hunk 1]
```diff
@@ -17,9 +17,7 @@ const Geo: React.FC = () => {
   const cycle = useCycle()
   const user = useUser()
 
-  const hasRoleInCountry = Users.hasRoleInCountry({ cycle, countryIso, user })
-
-  if (!hasRoleInCountry) {
+  if (!Authorizer.canViewGeo({ cycle, countryIso, user })) {
```
Comment (sorja) [inline src/client/pages/Geo/Geo.tsx]: should we use hook useCanViewGeo

**Review by sorja — DISMISSED** [review]

File: src/client/pages/Geo/Geo.tsx (hunk 1 above)
Comment (minotogna) [reply src/client/pages/Geo/Geo.tsx]: sure.

**Review by yaguzmang — APPROVED** [review]
