### PR TITLE
3331 - Navigate to Cycle home from tutorials page on assessment change

### LINKED ISSUE #3331: Tutorial page: Switch cycle wrong link
When switching assessment or cycle from tutorial FRA 2025 page must link to cycle home.
Now links to tutorial page of target assessment/cycle which might not exists 

https://github.com/openforis/fra-platform/assets/1138156/d6e4136a-1890-445f-a28b-d3ac490fd2a3

https://github.com/openforis/fra-platform/assets/1138156/7b3b35b9-5c69-4364-a8bc-854bf34bfb07

### PR DESCRIPTION
**Pull request by yaguzmang**
Closes #3331 

Changed the cycle switcher links to always point to the Cycle home if the user is in the the tutorials page. 

https://github.com/openforis/fra-platform/assets/41337901/7a75d662-acf5-4237-94be-d61a647d0a14

### CODE REVIEW

**Comment by minotogna** [comment]
@yaguzmang in the PR title we use the convention 😀 
Issue number - short description 

This helps us to keep on order commit history as well

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/useNavigateTo.tsx [hunk 1]
```diff
@@ -21,13 +24,14 @@ export const useNavigateTo = () => {
       const hasRoleInCountry = Users.hasRoleInCountry({ user, cycle, countryIso })
 
       let link = ''
-      if (countryIso && (cycle.published || hasRoleInCountry))
+      if (isTutorialsRoute) link = Routes.Cycle.generatePath({ assessmentName, cycleName })
```
Comment (minotogna) [inline src/client/components/PageLayout/Header/CycleSwitcher/hooks/useNavigateTo.tsx]: I wouldn't really add a specific case for each page . Otherwise every new page will be needed to be handled here .

I'd rather try to fix the generic rule

**Review by minotogna — CHANGES_REQUESTED** [review]

File: src/client/components/PageLayout/Header/CycleSwitcher/hooks/useNavigateTo.tsx (hunk 1 above)
Comment (yaguzmang) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/useNavigateTo.tsx]: Okay! By generic rule do you mean the code here or in the routing system?
In this line specifically, this would be a especial case like `else if (isAdminPage)`3 lines below.

Comment (minotogna) [reply src/client/components/PageLayout/Header/CycleSwitcher/hooks/useNavigateTo.tsx]: countryIso at line 15 should be taken from hook useCountryRouteParams . and don't manage custom isTutorialPage

**Review by minotogna — APPROVED** [review]
