### PR TITLE
add fixes

### LINKED ISSUE #2724: [PanEuropean] Country Coments table 4.4.2 are not being imported

### LINKED ISSUE #2725: [PanEuropean] Change table layout (CC 1.1 and table 2.5)

### PR DESCRIPTION
**Pull request by persas**
Closes #2725 
Closes #2724

### CODE REVIEW

File: src/server/db/db.ts [hunk 1]
```diff
@@ -1,16 +1,9 @@
...
 
-const debugOptions = {
-  query: (e: pgPromise.IEventContext) => {
-    Logger.debug(`QUERY: ${e.query}`)
-    if (e.params) {
-      Logger.debug(`PARAMS: ${JSON.stringify(e.params)}`)
-    }
-  },
-}
+const debugOptions = {}
```
Comment (minotogna) [inline src/server/db/db.ts]: I would rollback this change. is it possible ?

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]
