### PR TITLE
datatable/Chart: Fix issues with chart:

### LINKED ISSUE #1278: ODP Chart not rendered when toggling 'hide national data points'
https://user-images.githubusercontent.com/1138156/164296558-d50bb3a1-919d-4009-9848-509267af6d00.mov

### PR DESCRIPTION
**Pull request by sorja**
resolves #1278

### CODE REVIEW

File: client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx [hunk 1]
```diff
@@ -30,17 +30,19 @@ const toObject = (x) => {
   Object.entries(x).forEach(([countryIso, countryValues]) => {
     Object.entries(countryValues).forEach(([section, sectionValues]) => {
       Object.entries(sectionValues).forEach(([year, yearValues]: any[]) => {
+        // Display chart for section 1a and 1b
+        if (!['extentOfForest', 'forestCharacteristics'].includes(section)) return
```
Comment (minotogna) [inline client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx:34]: why hardcode this?

Comment (sorja) [reply client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx:34]: Do we have information in metadata which should show chart?

Comment (sorja) [reply client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx:34]: Maybe `table.props.odp` = show chart?

**Review by minotogna — APPROVED** [review]
