### PR TITLE
ODP Errors: Use tooltip and hide in printview

### LINKED ISSUE #2999: High priority - Error messages are printed out for FRA 2020 report
@minotogna 
**Describe the bug**
Error messages are printed out for FRA 2020 report.

**To Reproduce**
Example of Benin:
1.Go to https://fra-data.fao.org/assessments/fra/2020/BEN/print/
2.Check 1b

**Expected behavior**
Errors should be hidden for the public access.

**Screenshots**

### PR DESCRIPTION
**Pull request by sorja**
chrome_QUu576la9A

### CODE REVIEW

File: src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  const { print } = useIsPrintRoute()
+
+  const hasErrors = nationalClassValidations.some((v) => !v[variable])
+
+  const { t } = useTranslation()
+
+  const nationalClassValidation = nationalClassValidations[index]
+
+  // don't show errors if user is not logged in or if it is print view
+  if (!hasErrors || !user || print || nationalClassValidation[variable]) {
```
Comment (minotogna) [inline src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts]: please note, to see errors user must have edit permissions

Comment (minotogna) [reply src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts]: see table errors

File: src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+type Props = {
+  originalDataPoint: OriginalDataPoint
+  index: number
+  variable: keyof NationalClassValidation
+}
+export const useNationalClassValidations = (props: Props) => {
+  const { originalDataPoint, variable, index } = props
+  const { nationalClasses } = props.originalDataPoint
+  const nationalClassValidations = nationalClasses.map((_, index) =>
```
Comment (minotogna) [inline src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts]: I wouldn't even validate if condition for validate is not match

File: src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import { useIsPrintRoute } from 'client/hooks/useIsRoute'
+
+type Props = {
+  originalDataPoint: OriginalDataPoint
+  index: number
+  variable: keyof NationalClassValidation
+}
+export const useNationalClassValidations = (props: Props) => {
+  const { originalDataPoint, variable, index } = props
+  const { nationalClasses } = props.originalDataPoint
```
Comment (minotogna) [inline src/client/pages/OriginalDataPoint/hooks/useNationalClassValidations.ts]: I wouldn't extract national classes. plus originalDataPoint is extracted above

**Review by minotogna — APPROVED** [review]
