### PR TITLE
Fix user language selection

### LINKED ISSUE #1485: Arabic version

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1485 

https://user-images.githubusercontent.com/5508251/188627127-315c6b94-7144-4c89-b685-edb10f3545fa.mov

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
can we get a video of the platform in ar ?

**Comment by sorja** [comment]
Uploaded low quality(480p) video (100mb limit)

**Review by minotogna — APPROVED** [review]

File: src/client/components/Header/LanguageSelector/LanguageSelector.tsx [hunk 1]
```diff
@@ -1,17 +1,19 @@
...
+import PopoverControl from '@client/components/PopoverControl'
 
 const LanguageSelector: React.FC = () => {
   const { i18n } = useTranslation()
 
   const updateLanguage = async (lang: Lang) => {
     await i18n.changeLanguage(lang)
     await localStorage.setItem('i18n/lang', lang)
+    if (lang === 'ar') document.body.classList.add('rtl')
+    if (lang !== 'ar') document.body.classList.remove('rtl')
```
Comment (rfontanarosa) [inline src/client/components/Header/LanguageSelector/LanguageSelector.tsx:16]: else

**Review by rfontanarosa — APPROVED** [review]
