### PR TITLE
2741 - TotalForestArea explicit calculation

### LINKED ISSUE #2741: South Sudan - calculation error - T1b (High priority)
@minotogna 

For 2025, the calculation of **Naturally regenerating forest (a)**  and **Planted forest (b=b1+b2)** is not equal to **Planted forest (b=b1+b2)** for South Sudan.

Wrong cal:

Right cal:

Considering this as high priority since the country has tried to finalized the report.

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #2741

### CODE REVIEW

File: src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts [hunk 1]
```diff
@@ -17,6 +17,8 @@ export class MemberEvaluator extends ExpressionNodeEvaluator<Context, MemberExpr
 
     const memberVariable = ExpressionEvaluator.parseMemberVariable(expressionNode)
 
+    const { tableName: _tableName, variableName: _variableName } = memberVariable
+
```
Comment (sorja) [inline src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts]: Looks ok, dont use _tableName but use directly memberVariable.tableName where _tableName is used

Thanks for catching this typo

File: src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts [hunk 2]
```diff
@@ -27,18 +29,15 @@ export class MemberEvaluator extends ExpressionNodeEvaluator<Context, MemberExpr
       ) {
         assessmentMetaCache[type].dependants = {
           ...assessmentMetaCache[type].dependants,
-          // @ts-ignore
           [_tableName]: {
             ...dependantTable,
-            // @ts-ignore
             [_variableName]: [...dependants, dependant],
```
Comment (sorja) [inline src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts]: here memberVariable.variableName

File: src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts [hunk 3]
```diff
@@ -27,18 +29,15 @@ export class MemberEvaluator extends ExpressionNodeEvaluator<Context, MemberExpr
       ) {
         assessmentMetaCache[type].dependants = {
           ...assessmentMetaCache[type].dependants,
-          // @ts-ignore
           [_tableName]: {
```
Comment (sorja) [inline src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts]: here memberVariable.tableName

**Review by sorja — APPROVED** [review]

**Review by minotogna — APPROVED** [review]
