### PR TITLE
Meta/invitation gmail fix

### LINKED ISSUE #1806: user invitation : check if user has google auth with invited email
Country home -> manage collaborators 

When inviting user , the email must be used to verify if it’s used by a user with google login as well 
If that’s the case , the invitation belongs to that user and email should be sent to his primary email

### PR DESCRIPTION
**Pull request by sorja**
Resolves #1806 

includes region role fix

image

### CODE REVIEW

**Review by rfontanarosa — APPROVED** [review]

File: src/server/controller/user/invite.ts [hunk 1]
```diff
@@ -40,7 +41,8 @@ export const invite = async (
       t
     )
 
-    userToInvite = await UserRepository.getOne({ email }, t)
+    userToInvite =
```
Comment (minotogna) [inline src/server/controller/user/invite.ts]: is this fetch really needed? isn't the user to invite correctly initialized above?

Comment (minotogna) [reply src/server/controller/user/invite.ts]: the thing to make sure is that UserRepository.create returns the same object than UserRepository.getOne

**Review by minotogna — APPROVED** [review]
