### PR TITLE
4263 - PDF - T1b data fetching

### LINKED ISSUE #4263: PDF - T1b data fetching
@minotogna 

**Describe the bug**
For countries that adopt NDP in both Table 1a and Table 1b, data for the reclassification of '...of which primary forest' and '...of which introduced' is fetched.

**To Reproduce**
Example of Australia
1. Go to Australia PDF report NDP - Original data and reclassification
2. See error

**Expected behavior**
The data is properly fetched and displayed.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

File: src/client/components/EditorWYSIWYG/EditorWYSIWYGLinks/EditorWYSIWYGLinks.tsx [hunk 1]
```diff
@@ -10,6 +13,11 @@ type Props = {
 }
 const EditorWYSIWYGLinks: React.FC<Props> = (props: Props) => {
   const { onChange, value, disabled, repository } = props
+  const { print } = useIsPrintRoute()
+
+  if (print) {
+    return <EditorWYSIWYGReadOnly value={value} />
+  }
```
Comment (sorja) [inline src/client/components/EditorWYSIWYG/EditorWYSIWYGLinks/EditorWYSIWYGLinks.tsx:20]: Bonus fix:
- Introduce `EditorWYSIWYGReadOnly` and use it also for `EditorWYSIWYGLinks`

**Review by minotogna — APPROVED** [review]
👍
