### PR TITLE
3602 - Fix Add NDP Button layout

### LINKED ISSUE #3602: Add national data point button layout broken
image

### PR DESCRIPTION
**Pull request by minotogna**
image

### CODE REVIEW

File: src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ const ExtentOfForest: React.FC = () => {
   const { assessmentName, cycleName, countryIso } = useCountryRouteParams<CountryIso>()
   const user = useUser()
   const disabled = !editEnabled
-  const className = useButtonClassName({ disabled, iconName: 'small-add', size: ButtonSize.m })
+  const className = useButtonClassName({ disabled, iconName: 'small-add', label: 'L', size: ButtonSize.m })
```
Comment (sorja) [inline src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx:21]: what is label L?

Comment (minotogna) [reply src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx:21]: it's just a fake label to instruct the css to have two columns. have a look on how the button class is built in case

Comment (sorja) [reply src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx:21]: Sure, I saw, it was a bit confusing

**Review by sorja — APPROVED** [review]

File: src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx (hunk 1 above)
Comment (minotogna) [reply src/client/pages/Section/SectionHeader/ExtentOfForest/ExtentOfForest.tsx:21]: What is confusing ?
