### PR TITLE
4619 - PDF - Remove table 3c 'if yes' col

### LINKED ISSUE #4619: Table 3c : remove 'If yes' column
@minotogna 

**Describe the bug**
Change 'if Yes' from vertical to horizontal?

Example: Findland page 38

Image

Image

Need to speak with the admin.

### PR DESCRIPTION
**Pull request by yaguzmang**
Before:
image

After:
image

### CODE REVIEW

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts [hunk 1]
```diff
@@ -0,0 +1,85 @@
+import { AssessmentNames } from 'meta/assessment/assessment'
+
+import { AssessmentController } from 'server/controller/assessment'
+import { BaseProtocol, Schemas } from 'server/db'
+
+const assessmentName = AssessmentNames.fra
+const cycleName = '2025'
```
Comment (minotogna) [inline src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: We need to update latest cycle as well .
Basically everywhere there's this table

Comment (yaguzmang) [reply src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: Okay so only fra latest pending as panEu doesn't have this `forestRestoration` table :+1:

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+         where r.props ->> 'type' = 'data'
+       and r.props ->> 'index' = '0'
+       and t.props ->> 'name' = '${tableName}'
+     )
+    `
+  )
+
+  // 3. Remove "if yes" cell
+  await client.query(
+    `update ${schemaAssessment}.col c
```
Comment (minotogna) [inline src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: Should we actually delete the col ?

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+
+  const cycleUuid = cycle.uuid
+  const schemaAssessment = Schemas.getName(assessment)
+
+  // 1. Update gridTemplateColumns
+  const gridTemplateColumns = 'minmax(min-content, 1fr) minmax(min-content, 2fr)'
+  await client.query(
+    `update ${schemaAssessment}.table
+     set props = jsonb_set(
+      jsonb_set(
```
Comment (minotogna) [inline src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: Is this inner jsonb set needed ?

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts (hunk 2 above)
Comment (yaguzmang) [reply src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: index
Sure. There was a lingering 2020 label, but it shouldn't matter since this table doesn't exist for 2020.

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts (hunk 3 above)
Comment (yaguzmang) [reply src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: Since we know both gridTemplateCols in the cycles exists, no. Removed it 👍

File: src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts (hunk 1 above)
Comment (minotogna) [reply src/test/migrations/steps/20250506132557-step-table-3c-remove-if-yes-col.ts]: Yes fra and panEuropean do not share any table . They are in 2 different schema

**Review by minotogna — APPROVED** [review]
