### PR TITLE
2641 - fix forestAreaChange table validation

### LINKED ISSUE #2641: Table 1d- validation error
@minotogna 

Check the validation:

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #2641

Screenshot 2023-05-17 alle 11 30 46

Screenshot 2023-05-17 alle 09 08 03

### CODE REVIEW

File: src/test/migrations/steps/20230517091206-step-fix-forest-area-change-validators.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+  await client.query(
+    `update ${schemaName}.row r set props = jsonb_set(r.props, '{validateFns, ${cycle.uuid}}',
+      ('[
+        "validatorSubCategory(forestAreaChange.forest_expansion, [forestAreaChange.natural_expansion])",
+        "validatorEqualToForestExpansion(forestAreaChange.forest_expansion, [forestAreaChange.afforestation, forestAreaChange.natural_expansion])"
+      ]'::text)::jsonb)
+    where id = $1;`,
+    ofWhichNaturalExpansion.id
+  )
+
```
Comment (minotogna) [inline src/test/migrations/steps/20230517091206-step-fix-forest-area-change-validators.ts:48]: I approve this pr , but it's a waste fetching first and then updating . It can be done in one query only . Performances of Data steps migrations must be taken into consideration to avoid deploy to production, as it happens with @sorja

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]
