### PR TITLE
4262 - PDF - T1b NDP printing

### LINKED ISSUE #4262: PDF - T1b NDP printing
@minotogna 

**Describe the bug**
The NDP of Table 1b should not be shown if the country chooses the NDP in Table 1a but opts **not to** use the NDP in Table 1b.

**To Reproduce**
1. Go to USA PDF report
2. Go down to the table 1b - National data
3. See the error should not presented here

**Screenshots**

Image

FRA platform USA report link:
https://fra-data.fao.org/assessments/fra/2025/USA/sections/forestCharacteristics

### PR DESCRIPTION
**Pull request by sorja**
Resolves [#4262](https://github.com/openforis/fra-platform/issues/4262)

### CODE REVIEW

File: src/client/pages/Section/Descriptions/CommentableDescription/hooks/useDescriptionErrorState.ts [hunk 1]
```diff
@@ -18,12 +19,14 @@ type Returned = {
 
 export const useDescriptionErrorState = (props: Props): Returned => {
   const { name, sectionName } = props
+  const { print } = useIsPrintRoute()
 
   const value = useCommentableDescriptionValue({ name, sectionName })
 
   return useMemo<Returned>(() => {
+    if (print) return { empty: false }
```
Comment (sorja) [inline src/client/pages/Section/Descriptions/CommentableDescription/hooks/useDescriptionErrorState.ts:27]: Fixes `too much recursion` error when printing e.g. USA
image

**Review by minotogna — APPROVED** [review]
