### PR TITLE
Fix admin paths

### LINKED ISSUE #139: Update admin routes
- [x] Use /admin for admin routes
- [x] Add route to basePaths
- [x] Update link using basePaths in webapp/app/components/header/components/userInfo.js

### PR DESCRIPTION
**Pull request by sorja**
Resolves #139

### CODE REVIEW

File: webapp/main/basePaths.js [hunk 1]
```diff
@@ -8,20 +8,58 @@ export const assessmentPrint = `${country}print/:assessmentType/`
 export const assessmentPrintOnlyTables = `${country}print/:assessmentType/onlyTables/`
 export const odp = `${country}odp/:tab/`
 export const user = '/users/:userId/'
+export const admin = '/admin/'
+
+const pathFragments = {
```
Comment (minotogna) [inline webapp/main/basePaths.js:13]: nice one. why not to use pathFragments in the routes above?
