### PR TITLE
3335 Activities: CountryIso and CycleUUID not null

### LINKED ISSUE #3335: Refresh materialized views job -> permanent failed
Image

Image

TODO:

- [ ] Fix the query in src/server/schedulers/initMaterializedViews -> _getActivityLogEntries to include only entries where country_iso and cycle_uuid are not null

### PR DESCRIPTION
**Pull request by sorja**
image

### CODE REVIEW

File: src/server/schedulers/initMaterializedViews.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ const _getActivityLogEntries = async (props: { jobTimestamp: number }): Promise<
   const jobCreatedAt = new Date(jobTimestamp).toISOString()
 
   const activities = await client.map<{ assessmentUuid: string; cycleUuid: string; countryIso: CountryIso }>(
-    `select assessment_uuid, cycle_uuid, country_iso from public.activity_log where time > $1 order by time desc`,
+    `select assessment_uuid, cycle_uuid, country_iso from public.activity_log where time > $1 country_iso is not null and cycle_uuid is not null order by time desc`,
```
Comment (minotogna) [inline src/server/schedulers/initMaterializedViews.ts]: isn't it `and country_iso...` ?
can we format the query a bit better ?

File: src/test/migrations/steps/20231221125643-step-fix-activity-log-tableValuesClear.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import { BaseProtocol } from 'server/db'
+
```
Comment (minotogna) [inline src/test/migrations/steps/20231221125643-step-fix-activity-log-tableValuesClear.ts:2]: do we need to update where this is generated as well ? (the controller clearTableValues)?

**Review by minotogna — APPROVED** [review]
